//! What the unit says when it blocks a transaction.
//!
//! **A fault is reported by an MSI the unit itself generates, never polled** —
//! a fault noticed a hundred milliseconds later is a
//! fault whose device has been retrying all along. The handler is bounded, does
//! no allocation and takes no lock; the units it reads live in a fixed array of
//! atomics, written once before the mask comes off and never again, which is
//! the same discipline mapping a source-id to a process will need.
//!
//! **A fault splits by whose stream it is on**: on a kernel stream it is a
//! kernel bug and stops the machine, on a userspace driver's stream it is a
//! driver bug and kills that process. There are no userspace drivers yet, so
//! every stream on the machine is kernel-owned and every fault takes the first
//! half. The kill path, the per-domain latch and the `need_resched` handoff
//! that go with the second half arrive with per-driver domains, along with
//! something to attach them to.
//!
//! Clearing Bus Master Enable on the offending function — what lets that
//! handler stay bounded — is not done here for the same reason.
//! The next thing this path does is halt every CPU, so a device that has been
//! told to stop and a machine that has stopped are indistinguishable, and the
//! store would be a line no configuration in reach can show doing anything.

use core::sync::atomic::{AtomicU32, AtomicU64, Ordering};

use crate::iommu::StreamId;
use crate::mm::{DirectMap, Mmio};

use super::{
    FECTL_REG, FEADDR_REG, FEDATA_REG, FEUADDR_REG, FSTS_REG, MAX_UNITS, REGISTER_WINDOW,
};

/// The LAPIC window, physical destination 0, fixed delivery, edge — the same
/// address every device MSI in this kernel targets. The unit's fault event is
/// generated by the remapping hardware rather than by a device, so it is the
/// one message interrupt that interrupt remapping must not block — and until
/// `GCMD.CFI` is cleared nothing blocks it.
const MSG_ADDR: u32 = 0xFEE0_0000;

/// `FSTS` bits this kernel clears by writing them back. Everything else in the
/// register is read-only status.
const FSTS_WRITE_ONE_TO_CLEAR: u32 = 0x7F;
/// `FSTS.PPF`: at least one fault recording register has its `F` bit set.
const FSTS_PENDING: u32 = 1 << 1;
/// `FSTS.PFO`: a fault arrived with every recording register already full, so
/// what it was is gone. Worth a line of its own — a count that stops rising is
/// otherwise indistinguishable from a storm that stopped.
const FSTS_OVERFLOW: u32 = 1 << 0;

/// One fault recording register's `F` bit, in the 32-bit word that carries it.
const RECORD_FAULT: u32 = 1 << 31;

/// A programmed unit, in the shape an interrupt handler can read.
///
/// Three atomics rather than the `Mmio` handle itself: the handler may take no
/// lock, so a `Lock<Vec<Unit>>` is not reachable from it, and these are written
/// once during the boot phase that programs the unit — before its mask comes
/// off, so there is no moment at which the handler can see half of one.
///
/// **The window is rebuilt from the address rather than dereferenced through
/// it.** An `Mmio` is two words and no atomic holds two, but the second word is
/// [`REGISTER_WINDOW`] for every unit there is, so the address is the whole of
/// what has to be published — and [`Mmio::over_phys`] turns it back into a
/// window whose bound the handler's every read and write is checked against.
struct FaultUnit {
    /// *Physical* base of the register window, or 0 for a slot no unit uses.
    ///
    /// Physical and not virtual because that is what rebuilds the window, and
    /// zero is the sentinel: `vtd::window` refuses a register base of 0 before
    /// a unit is ever described, so no armed unit can have one.
    regs: AtomicU64,
    /// Where the first fault recording register sits *inside* that window —
    /// `CAP.FRO`, which is how it was declared in the first place.
    records: AtomicU64,
    /// How many there are.
    count: AtomicU32,
}

impl FaultUnit {
    // A `const` holding atomics is copied at each use, so a write through one
    // would go nowhere. This one is never written and never borrowed: its single
    // use is the array repeat below, and every store in this file names
    // `UNITS[index]`, which is the `static`. `borrow_interior_mutable_const`,
    // the lint that fires on the losing-a-write shape, is silent here.
    #[allow(clippy::declare_interior_mutable_const)]
    const EMPTY: Self =
        Self { regs: AtomicU64::new(0), records: AtomicU64::new(0), count: AtomicU32::new(0) };
}

static UNITS: [FaultUnit; MAX_UNITS] = [const { FaultUnit::EMPTY }; MAX_UNITS];

/// Where a unit keeps its fault records and how many it has: `CAP.FRO` and
/// `CAP.NFR`, carried together because neither is usable without the other.
#[derive(Clone, Copy)]
pub struct Records {
    pub offset: u64,
    pub count: u32,
}

impl Records {
    /// Whether they fit the window this kernel maps for the unit.
    ///
    /// These are the unit's own numbers and are checked like any other
    /// device's: one claiming 256 records at an offset near the top of the
    /// window describes a range past the 4 KiB that is mapped. Such a unit is
    /// refused by name here, rather than served with a walk truncated to fit —
    /// and rather than left to the window's own bound, which would notice the
    /// same thing as a panic in an interrupt handler and say nothing about
    /// which register made the claim.
    pub fn fit(self, window: u64) -> bool {
        self.offset + self.count as u64 * 16 <= window
    }
}

/// Point the unit's fault event at this kernel and take the mask off.
///
/// Before translation is enabled, so the very first transaction the unit blocks
/// is one it can report.
pub fn arm(index: usize, regs: Mmio, found: Records, vector: u8) {
    let count = found.count;

    // Firmware may have left records behind — its own DMA remapping, or a warm
    // reset. Cleared before the mask comes off, so the first event this kernel
    // takes is about a transaction this kernel's tables blocked.
    for i in 0..count {
        clear_record(regs, found.offset + i as u64 * 16);
    }
    let stale = regs.read_u32(FSTS_REG);
    regs.write_u32(FSTS_REG, stale & FSTS_WRITE_ONE_TO_CLEAR);

    UNITS[index].records.store(found.offset, Ordering::Relaxed);
    UNITS[index].count.store(count, Ordering::Relaxed);
    // Last, and with a release: it is what the handler tests, so every field it
    // will read has to be in place before this one is.
    UNITS[index].regs.store(DirectMap::phys_of(regs.addr() as *const u8), Ordering::Release);

    regs.write_u32(FEDATA_REG, vector as u32);
    regs.write_u32(FEADDR_REG, MSG_ADDR);
    regs.write_u32(FEUADDR_REG, 0);
    regs.write_u32(FECTL_REG, 0);
}

/// The window an armed unit's registers live in, from the address [`arm`]
/// published.
fn window(phys: u64) -> Mmio {
    // SAFETY: `phys` is the physical base `vtd::window` handed to
    // `paging::map_mmio`, republished here by `arm` — a `REGISTER_WINDOW`-wide
    // mapping this kernel made at boot and never unmaps, checked against
    // `MAX_PHYS` and 4 KiB alignment before it was mapped at all. Volatile is
    // what a register access has to be, which is `over_phys`'s other half.
    unsafe { Mmio::over_phys(DirectMap::from_phys(phys), REGISTER_WINDOW) }
}

/// The unit raised its fault event.
pub fn service() {
    let mut faults = 0usize;
    for (index, unit) in UNITS.iter().enumerate() {
        let phys = unit.regs.load(Ordering::Acquire);
        if phys == 0 {
            continue;
        }
        faults += drain(
            index,
            window(phys),
            unit.records.load(Ordering::Relaxed),
            unit.count.load(Ordering::Relaxed),
        );
    }

    if faults > 0 {
        // Every stream on this machine is kernel-owned, so this is a kernel
        // bug and the machine stops. The capture is what puts the lines above
        // on the panel of a machine with no serial port, which is where this
        // one will be read.
        crate::drivers::panic_console::capture();
        crate::arch::apic::halt_all_cpus();
    }
    crate::arch::apic::eoi();
}

fn drain(index: usize, regs: Mmio, records: u64, count: u32) -> usize {
    let status = regs.read_u32(FSTS_REG);
    if status & FSTS_OVERFLOW != 0 {
        log!("iommu: unit{index} fault recording overflowed — earlier faults are lost");
    }
    if status & FSTS_PENDING == 0 {
        regs.write_u32(FSTS_REG, status & FSTS_WRITE_ONE_TO_CLEAR);
        return 0;
    }

    let mut seen = 0usize;
    for i in 0..count {
        let record = records + i as u64 * 16;
        let high = regs.read_u64(record + 8);
        if high & (1u64 << 63) == 0 {
            continue;
        }
        let stream = StreamId::pci(
            (high >> 8) as u8,
            ((high >> 3) & 0x1F) as u8,
            (high & 0x7) as u8,
        );
        let reason = ((high >> 32) & 0xFF) as u8;
        log!(
            "iommu: DMA FAULT unit{index} stream={stream} addr={:#018x} access={} reason={reason:#04x} {}",
            regs.read_u64(record) & !0xFFF,
            if high & (1u64 << 62) != 0 { "read" } else { "write" },
            reason_name(reason),
        );
        clear_record(regs, record);
        seen += 1;
    }
    regs.write_u32(FSTS_REG, status & FSTS_WRITE_ONE_TO_CLEAR);
    seen
}

fn clear_record(regs: Mmio, record: u64) {
    regs.write_u32(record + 12, RECORD_FAULT);
}

/// The reasons worth a name rather than a number.
///
/// The raw code is printed either way, so a name is a convenience and never
/// the record. Only codes on which the two independent decoders in reach —
/// Linux's `dma_remap_fault_reasons` and QEMU's `VTD_FR_*` — say the same
/// thing get one; 0x0c and 0x0d are where they disagree, and a name invented
/// to fill the gap would be the plausible wrong constant the spec warns about
/// outliving every review. Two of these are not cited but *observed*: the
/// harness stages a function with no context entry and one whose domain has no
/// mappings, and asserts the unit's own record decodes to 0x02 and — on QEMU,
/// which judges an all-zero second-level entry on its permission bits rather
/// than on a present bit — 0x06.
fn reason_name(reason: u8) -> &'static str {
    match reason {
        0x01 => "root-entry-not-present",
        0x02 => "context-entry-not-present",
        0x03 => "context-entry-invalid",
        0x04 => "address-beyond-mgaw",
        0x05 => "write-permission",
        0x06 => "read-permission",
        0x07 => "paging-entry-invalid",
        0x08 => "root-table-unreadable",
        0x09 => "context-table-unreadable",
        0x0A => "reserved-bits-in-root-entry",
        0x0B => "reserved-bits-in-context-entry",
        0x20 => "reserved-bits-in-remapped-interrupt",
        0x21 => "interrupt-index-beyond-table",
        0x22 => "interrupt-entry-not-present",
        0x23 => "interrupt-table-unreadable",
        0x24 => "reserved-bits-in-interrupt-entry",
        0x25 => "compatibility-format-interrupt-blocked",
        0x26 => "interrupt-source-id-verification-failed",
        _ => "unnamed",
    }
}
