//! Vt-d fault interrupt handling: MSI-delivered, never polled.
//!
//! The handler is bounded, allocates nothing and takes no lock; unit and
//! function state lives in fixed arrays of atomics, written once before the
//! mask comes off. Every stream is kernel-owned, so the terminal action is
//! still a halt — a kernel driver reaching outside its domain is a kernel bug —
//! but the halt is now the last thing that happens rather than the first.
//!
//! Before it: Bus Master Enable cleared on the function that faulted, the first
//! record latched whole, and a count kept per unit and per function. Clearing
//! `BME` is also the ceiling on a storm, since a function that cannot master
//! the bus cannot raise a second fault (PCI 3.0 §6.2.2, bit 2 of `COMMAND`).
//!
//! The reschedule handoff the track lists is not here: with the terminal action
//! a halt there is nothing on the other side of it to hand to, and it lands
//! with the process-kill arm that gives it one.

use core::sync::atomic::{AtomicU32, AtomicU64, Ordering};

use crate::drivers::pci::{self, PciDevice};
use crate::iommu::StreamId;
use crate::mm::{DirectMap, Mmio};

use super::{
    FECTL_REG, FEADDR_REG, FEDATA_REG, FEUADDR_REG, FSTS_REG, MAX_UNITS, REGISTER_WINDOW,
};

// LAPIC destination every device MSI in this kernel targets.
// The unit's own fault event is generated by the remapping hardware itself, so interrupt remapping never blocks it.
const MSG_ADDR: u32 = 0xFEE0_0000;

// Write-1-to-clear bits; the rest of FSTS is read-only status.
const FSTS_WRITE_ONE_TO_CLEAR: u32 = 0x7F;
// FSTS.PPF: a fault recording register has its F bit set.
const FSTS_PENDING: u32 = 1 << 1;
// FSTS.PFO: a fault arrived with every recording register already full.
const FSTS_OVERFLOW: u32 = 1 << 0;

// One fault recording register's F bit, in the 32-bit word that carries it.
const RECORD_FAULT: u32 = 1 << 31;

// Atomics only: the handler takes no lock; each field is written once before
// the unit's mask comes off.
struct FaultUnit {
    // Physical base of the register window; 0 means this slot is unused.
    // vtd::window refuses a base of 0, so no armed unit can collide with the sentinel.
    regs: AtomicU64,
    // Offset of the first fault recording register within the window (CAP.FRO).
    records: AtomicU64,
    count: AtomicU32,
    // Faults this unit has reported for the life of the boot.
    faults: AtomicU32,
}

impl FaultUnit {
    // EMPTY is copied per use and never written; every real write goes
    // through `UNITS[index]`, the static.
    #[allow(clippy::declare_interior_mutable_const)]
    const EMPTY: Self = Self {
        regs: AtomicU64::new(0),
        records: AtomicU64::new(0),
        count: AtomicU32::new(0),
        faults: AtomicU32::new(0),
    };
}

static UNITS: [FaultUnit; MAX_UNITS] = [const { FaultUnit::EMPTY }; MAX_UNITS];

/// Functions the handler can act on. A machine with more than this many
/// enumerated is told; the ones past it keep bus mastering through a fault,
/// which is a worse machine than one that is refused a name for it.
const MAX_FUNCTIONS: usize = 64;

/// A requester id no `StreamId::pci` produces: bus/device/function is sixteen bits.
const NO_FUNCTION: u32 = u32::MAX;

/// One enumerated function, published before any unit is armed.
struct Function {
    // `NO_FUNCTION` while the slot is free; a requester id once taken.
    who: AtomicU32,
    // Physical base of its 4 KiB config window, the same round trip `regs` takes.
    config: AtomicU64,
    // The domain it was last attached to, or 0 while it is on the identity domain.
    domain: AtomicU32,
    // Faults the unit has reported against it; non-zero is the per-domain flag.
    faults: AtomicU32,
}

impl Function {
    #[allow(clippy::declare_interior_mutable_const)]
    const EMPTY: Self = Self {
        who: AtomicU32::new(NO_FUNCTION),
        config: AtomicU64::new(0),
        domain: AtomicU32::new(0),
        faults: AtomicU32::new(0),
    };
}

static FUNCTIONS: [Function; MAX_FUNCTIONS] = [const { Function::EMPTY }; MAX_FUNCTIONS];

/// The first fault this machine took, whole. Latched rather than only counted:
/// what a later one says is decided by what the first one already broke.
struct FirstFault {
    // `NO_FUNCTION` until one is taken; the requester id afterwards.
    who: AtomicU32,
    address: AtomicU64,
    reason: AtomicU32,
    unit: AtomicU32,
}

static FIRST: FirstFault = FirstFault {
    who: AtomicU32::new(NO_FUNCTION),
    address: AtomicU64::new(0),
    reason: AtomicU32::new(0),
    unit: AtomicU32::new(0),
};

/// Every function this machine enumerated, before any unit is armed, so the
/// handler can reach the config space of whoever faults without a lock.
pub fn describe(devices: &[PciDevice]) {
    for (slot, device) in FUNCTIONS.iter().zip(devices) {
        let stream = StreamId::pci(device.bus, device.dev, device.func);
        slot.config.store(
            DirectMap::phys_of(device.config_window().addr() as *const u8),
            Ordering::Relaxed,
        );
        // Last, with Release: `who` is what the handler tests, so `config` must
        // already be visible to whoever sees it.
        slot.who.store(u32::from(stream.requester()), Ordering::Release);
    }
    if devices.len() > MAX_FUNCTIONS {
        log!(
            "iommu: {} functions enumerated, past the {MAX_FUNCTIONS} the fault handler can \
             stop — the rest keep bus mastering through a fault",
            devices.len()
        );
    }
}

/// Record which domain a function moved to, for the flag the handler sets.
pub fn attached(stream: StreamId, domain: u16) {
    if let Some(slot) = find(u32::from(stream.requester())) {
        slot.domain.store(u32::from(domain), Ordering::Relaxed);
    }
}

fn find(requester: u32) -> Option<&'static Function> {
    FUNCTIONS.iter().find(|f| f.who.load(Ordering::Acquire) == requester)
}

/// A unit's fault-record location and count: `CAP.FRO` and `CAP.NFR`.
#[derive(Clone, Copy)]
pub struct Records {
    pub offset: u64,
    pub count: u32,
}

impl Records {
    /// Whether these fit the window this kernel maps for the unit.
    pub fn fit(self, window: u64) -> bool {
        self.offset + self.count as u64 * 16 <= window
    }
}

/// Point the unit's fault event at this kernel and unmask it, before
/// translation is enabled.
pub fn arm(index: usize, regs: Mmio, found: Records, vector: u8) {
    let count = found.count;

    // Clear records firmware may have left behind before unmasking.
    for i in 0..count {
        clear_record(regs, found.offset + i as u64 * 16);
    }
    let stale = regs.read_u32(FSTS_REG);
    regs.write_u32(FSTS_REG, stale & FSTS_WRITE_ONE_TO_CLEAR);

    UNITS[index].records.store(found.offset, Ordering::Relaxed);
    UNITS[index].count.store(count, Ordering::Relaxed);
    // Store last, with Release: the handler tests this field, so every other
    // field it reads must already be visible.
    UNITS[index].regs.store(DirectMap::phys_of(regs.addr() as *const u8), Ordering::Release);

    regs.write_u32(FEDATA_REG, vector as u32);
    regs.write_u32(FEADDR_REG, MSG_ADDR);
    regs.write_u32(FEUADDR_REG, 0);
    regs.write_u32(FECTL_REG, 0);
}

/// One PCI function's config space, ECAM's stride.
const CONFIG_WINDOW: u64 = crate::mm::PAGE_SIZE;

// The window an armed unit's registers live in, from the address `arm` published.
fn window(phys: u64) -> Mmio {
    window_of(phys, REGISTER_WINDOW)
}

fn window_of(phys: u64, size: u64) -> Mmio {
    // SAFETY: `phys` came from `DirectMap::phys_of` over a window
    // `paging::map_mmio` produced at boot and never unmapped, `size` bytes wide;
    // this is the same window read back.
    unsafe { Mmio::over_phys(DirectMap::from_phys(phys), size) }
}

/// The unit raised its fault event.
pub fn service() {
    let mut faults = 0usize;
    for (index, unit) in UNITS.iter().enumerate() {
        let phys = unit.regs.load(Ordering::Acquire);
        if phys == 0 {
            continue;
        }
        faults += drain(
            index,
            window(phys),
            unit.records.load(Ordering::Relaxed),
            unit.count.load(Ordering::Relaxed),
        );
    }

    if faults > 0 {
        // capture() puts the fault on the panel before the halt takes the
        // machine down.
        crate::drivers::panic_console::capture();
        crate::arch::apic::halt_all_cpus();
    }
    crate::arch::apic::eoi();
}

fn drain(index: usize, regs: Mmio, records: u64, count: u32) -> usize {
    let status = regs.read_u32(FSTS_REG);
    if status & FSTS_OVERFLOW != 0 {
        log!("iommu: unit{index} fault recording overflowed — earlier faults are lost");
    }
    if status & FSTS_PENDING == 0 {
        regs.write_u32(FSTS_REG, status & FSTS_WRITE_ONE_TO_CLEAR);
        return 0;
    }

    let mut seen = 0usize;
    for i in 0..count {
        let record = records + i as u64 * 16;
        let high = regs.read_u64(record + 8);
        if high & (1u64 << 63) == 0 {
            continue;
        }
        let stream = StreamId::pci(
            (high >> 8) as u8,
            ((high >> 3) & 0x1F) as u8,
            (high & 0x7) as u8,
        );
        let reason = ((high >> 32) & 0xFF) as u8;
        let address = regs.read_u64(record) & !0xFFF;
        // First, before anything that can be slow or say no: a function that
        // cannot master the bus raises no second fault, which is the whole of
        // the ceiling on a storm.
        let stopped = stop(stream);
        let seen_here = note(stream);
        latch(index, stream, address, reason);
        let count = UNITS[index].faults.fetch_add(1, Ordering::Relaxed) + 1;
        log!(
            // The reason's name stays the last word on the line: it is what
            // every gate that reads a fault takes the reason from.
            "iommu: DMA FAULT unit{index} stream={stream} addr={address:#018x} access={} \
             reason={reason:#04x} domain={} bme={} unitfaults={count} streamfaults={seen_here} \
             first={} {}",
            if high & (1u64 << 62) != 0 { "read" } else { "write" },
            find(u32::from(stream.requester()))
                .map_or(0, |f| f.domain.load(Ordering::Relaxed)),
            if stopped { "cleared" } else { "unknown-function" },
            yn(FIRST.who.load(Ordering::Relaxed) == u32::from(stream.requester())),
            reason_name(reason),
        );
        clear_record(regs, record);
        seen += 1;
    }
    regs.write_u32(FSTS_REG, status & FSTS_WRITE_ONE_TO_CLEAR);
    seen
}

fn clear_record(regs: Mmio, record: u64) {
    regs.write_u32(record + 12, RECORD_FAULT);
}

/// Clear Bus Master Enable on whoever faulted; `false` where this machine
/// enumerated no function with that requester id, which is a fault from
/// something the kernel cannot stop and the line says so.
fn stop(stream: StreamId) -> bool {
    let Some(slot) = find(u32::from(stream.requester())) else {
        return false;
    };
    let config = slot.config.load(Ordering::Relaxed);
    pci::stop_bus_mastering(window_of(config, CONFIG_WINDOW));
    true
}

/// Count this fault against the function, and so against the domain it is in.
fn note(stream: StreamId) -> u32 {
    find(u32::from(stream.requester()))
        .map_or(0, |slot| slot.faults.fetch_add(1, Ordering::Relaxed) + 1)
}

/// Take the first fault whole, once. A second one finds `who` taken and leaves
/// it, so what is latched is the fault that started it rather than the last.
fn latch(unit: usize, stream: StreamId, address: u64, reason: u8) {
    let taken = FIRST.who.compare_exchange(
        NO_FUNCTION,
        u32::from(stream.requester()),
        Ordering::AcqRel,
        Ordering::Relaxed,
    );
    if taken.is_ok() {
        FIRST.address.store(address, Ordering::Relaxed);
        FIRST.reason.store(u32::from(reason), Ordering::Relaxed);
        FIRST.unit.store(unit as u32, Ordering::Relaxed);
    }
}

fn yn(v: bool) -> char {
    if v {
        'y'
    } else {
        'n'
    }
}

// Only reasons where Linux's dma_remap_fault_reasons and QEMU's VTD_FR_*
// agree get a name; 0x0c and 0x0d disagree and are left unnamed.
fn reason_name(reason: u8) -> &'static str {
    match reason {
        0x01 => "root-entry-not-present",
        0x02 => "context-entry-not-present",
        0x03 => "context-entry-invalid",
        0x04 => "address-beyond-mgaw",
        0x05 => "write-permission",
        0x06 => "read-permission",
        0x07 => "paging-entry-invalid",
        0x08 => "root-table-unreadable",
        0x09 => "context-table-unreadable",
        0x0A => "reserved-bits-in-root-entry",
        0x0B => "reserved-bits-in-context-entry",
        0x20 => "reserved-bits-in-remapped-interrupt",
        0x21 => "interrupt-index-beyond-table",
        0x22 => "interrupt-entry-not-present",
        0x23 => "interrupt-table-unreadable",
        0x24 => "reserved-bits-in-interrupt-entry",
        0x25 => "compatibility-format-interrupt-blocked",
        0x26 => "interrupt-source-id-verification-failed",
        _ => "unnamed",
    }
}
