//! Vt-d fault interrupt handling: MSI-delivered, never polled.
//!
//! The handler is bounded, allocates nothing and takes no lock; unit state
//! lives in a fixed array of atomics, written once before the mask comes off.
//! Every stream is kernel-owned, so a fault halts the machine.

use core::sync::atomic::{AtomicU32, AtomicU64, Ordering};

use crate::iommu::StreamId;
use crate::mm::{DirectMap, Mmio};

use super::{
    FECTL_REG, FEADDR_REG, FEDATA_REG, FEUADDR_REG, FSTS_REG, MAX_UNITS, REGISTER_WINDOW,
};

// LAPIC destination every device MSI in this kernel targets.
// The unit's own fault event is generated by the remapping hardware itself, so interrupt remapping never blocks it.
const MSG_ADDR: u32 = 0xFEE0_0000;

// Write-1-to-clear bits; the rest of FSTS is read-only status.
const FSTS_WRITE_ONE_TO_CLEAR: u32 = 0x7F;
// FSTS.PPF: a fault recording register has its F bit set.
const FSTS_PENDING: u32 = 1 << 1;
// FSTS.PFO: a fault arrived with every recording register already full.
const FSTS_OVERFLOW: u32 = 1 << 0;

// One fault recording register's F bit, in the 32-bit word that carries it.
const RECORD_FAULT: u32 = 1 << 31;

// Atomics only: the handler takes no lock; each field is written once before
// the unit's mask comes off.
struct FaultUnit {
    // Physical base of the register window; 0 means this slot is unused.
    // vtd::window refuses a base of 0, so no armed unit can collide with the sentinel.
    regs: AtomicU64,
    // Offset of the first fault recording register within the window (CAP.FRO).
    records: AtomicU64,
    count: AtomicU32,
}

impl FaultUnit {
    // EMPTY is copied per use and never written; every real write goes
    // through `UNITS[index]`, the static.
    #[allow(clippy::declare_interior_mutable_const)]
    const EMPTY: Self =
        Self { regs: AtomicU64::new(0), records: AtomicU64::new(0), count: AtomicU32::new(0) };
}

static UNITS: [FaultUnit; MAX_UNITS] = [const { FaultUnit::EMPTY }; MAX_UNITS];

/// A unit's fault-record location and count: `CAP.FRO` and `CAP.NFR`.
#[derive(Clone, Copy)]
pub struct Records {
    pub offset: u64,
    pub count: u32,
}

impl Records {
    /// Whether these fit the window this kernel maps for the unit.
    pub fn fit(self, window: u64) -> bool {
        self.offset + self.count as u64 * 16 <= window
    }
}

/// Point the unit's fault event at this kernel and unmask it, before
/// translation is enabled.
pub fn arm(index: usize, regs: Mmio, found: Records, vector: u8) {
    let count = found.count;

    // Clear records firmware may have left behind before unmasking.
    for i in 0..count {
        clear_record(regs, found.offset + i as u64 * 16);
    }
    let stale = regs.read_u32(FSTS_REG);
    regs.write_u32(FSTS_REG, stale & FSTS_WRITE_ONE_TO_CLEAR);

    UNITS[index].records.store(found.offset, Ordering::Relaxed);
    UNITS[index].count.store(count, Ordering::Relaxed);
    // Store last, with Release: the handler tests this field, so every other
    // field it reads must already be visible.
    UNITS[index].regs.store(DirectMap::phys_of(regs.addr() as *const u8), Ordering::Release);

    regs.write_u32(FEDATA_REG, vector as u32);
    regs.write_u32(FEADDR_REG, MSG_ADDR);
    regs.write_u32(FEUADDR_REG, 0);
    regs.write_u32(FECTL_REG, 0);
}

// The window an armed unit's registers live in, from the address `arm` published.
fn window(phys: u64) -> Mmio {
    // SAFETY: `phys` was mapped at boot by `vtd::window`/`paging::map_mmio`,
    // REGISTER_WINDOW-sized and never unmapped.
    unsafe { Mmio::over_phys(DirectMap::from_phys(phys), REGISTER_WINDOW) }
}

/// The unit raised its fault event.
pub fn service() {
    let mut faults = 0usize;
    for (index, unit) in UNITS.iter().enumerate() {
        let phys = unit.regs.load(Ordering::Acquire);
        if phys == 0 {
            continue;
        }
        faults += drain(
            index,
            window(phys),
            unit.records.load(Ordering::Relaxed),
            unit.count.load(Ordering::Relaxed),
        );
    }

    if faults > 0 {
        // capture() puts the fault on the panel before the halt takes the
        // machine down.
        crate::drivers::panic_console::capture();
        // Not clearing Bus Master Enable on the offending device: halting every CPU right after makes it unobservable.
        crate::arch::apic::halt_all_cpus();
    }
    crate::arch::apic::eoi();
}

fn drain(index: usize, regs: Mmio, records: u64, count: u32) -> usize {
    let status = regs.read_u32(FSTS_REG);
    if status & FSTS_OVERFLOW != 0 {
        log!("iommu: unit{index} fault recording overflowed — earlier faults are lost");
    }
    if status & FSTS_PENDING == 0 {
        regs.write_u32(FSTS_REG, status & FSTS_WRITE_ONE_TO_CLEAR);
        return 0;
    }

    let mut seen = 0usize;
    for i in 0..count {
        let record = records + i as u64 * 16;
        let high = regs.read_u64(record + 8);
        if high & (1u64 << 63) == 0 {
            continue;
        }
        let stream = StreamId::pci(
            (high >> 8) as u8,
            ((high >> 3) & 0x1F) as u8,
            (high & 0x7) as u8,
        );
        let reason = ((high >> 32) & 0xFF) as u8;
        log!(
            "iommu: DMA FAULT unit{index} stream={stream} addr={:#018x} access={} reason={reason:#04x} {}",
            regs.read_u64(record) & !0xFFF,
            if high & (1u64 << 62) != 0 { "read" } else { "write" },
            reason_name(reason),
        );
        clear_record(regs, record);
        seen += 1;
    }
    regs.write_u32(FSTS_REG, status & FSTS_WRITE_ONE_TO_CLEAR);
    seen
}

fn clear_record(regs: Mmio, record: u64) {
    regs.write_u32(record + 12, RECORD_FAULT);
}

// Only reasons where Linux's dma_remap_fault_reasons and QEMU's VTD_FR_*
// agree get a name; 0x0c and 0x0d disagree and are left unnamed.
fn reason_name(reason: u8) -> &'static str {
    match reason {
        0x01 => "root-entry-not-present",
        0x02 => "context-entry-not-present",
        0x03 => "context-entry-invalid",
        0x04 => "address-beyond-mgaw",
        0x05 => "write-permission",
        0x06 => "read-permission",
        0x07 => "paging-entry-invalid",
        0x08 => "root-table-unreadable",
        0x09 => "context-table-unreadable",
        0x0A => "reserved-bits-in-root-entry",
        0x0B => "reserved-bits-in-context-entry",
        0x20 => "reserved-bits-in-remapped-interrupt",
        0x21 => "interrupt-index-beyond-table",
        0x22 => "interrupt-entry-not-present",
        0x23 => "interrupt-table-unreadable",
        0x24 => "reserved-bits-in-interrupt-entry",
        0x25 => "compatibility-format-interrupt-blocked",
        0x26 => "interrupt-source-id-verification-failed",
        _ => "unnamed",
    }
}
