[package]
name = "netd"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
toyos-abi = { path = "../../toyos-abi" }
toyos = { path = "../../toyos" }
toyos-i219 = { path = "../../toyos-i219" }

[dependencies.smoltcp]
version = "0.12"
default-features = false
features = [
    "medium-ethernet",
    "proto-ipv4",
    "socket-tcp",
    "socket-udp",
    "socket-dns",
    "alloc",
]
