[package]
name = "soundd"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
toyos-abi = { path = "../../toyos-abi" }
toyos = { path = "../../toyos" }
toyos-hda = { path = "../../toyos-hda" }
toyos-mixer = { path = "../../toyos-mixer" }
toyos-inspect = { path = "../../toyos-inspect" }
rubato = "0.16"
