[package]
name = "toyos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "The ToyOS userland SDK: typed handles, IPC, ports, namespaces, surfaces and net."
repository = "https://github.com/ToyOSOrg/ToyOS"

[features]
rustc-dep-of-std = ["core", "toyos-abi/rustc-dep-of-std"]

[dependencies]
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
toyos-abi = { path = "../toyos-abi", version = "0.1.0", default-features = false }
