//! What the machine thinks the time is, and what it does when it cannot tell.
//!
//! The wall clock is one of the few devices the *host* can set, which is what
//! makes this checkable from outside the guest at all: `-rtc base=` puts a
//! known instant in the emulated CMOS before the machine starts, so the name
//! and the timestamp of the file the guest writes are both known before there
//! is a guest. The volume's verdicts are read off the disk image the device
//! received; the clock *syscalls* reach no disk, so what the guest printed for
//! those is judged against that same staged instant and nothing it derived.
//!
//! # What only an actuator can stage
//!
//! Four states of the clock, and the host can produce none of them: QEMU has no
//! switch that removes or wedges the mc146818, its RTC always presents the
//! guest a coherent register set, the FADT a guest reads is generated by QEMU
//! and always names the century register at 0x32, and `-rtc base=` sets every
//! digit of the date **except** the century. That last one is measured rather
//! than assumed: a guest booted with `base=2101-06-05` reads century 20 and
//! year 01 out of its own registers and correctly reports 2001, because QEMU
//! maintains the clock registers and leaves CMOS 0x32 at whatever firmware last
//! wrote there. So a staged year cannot distinguish a kernel that reads the
//! century register from one that assumes 2000 — [`no_century`] and
//! [`century_from_the_register`] are the two halves that can, and each is a
//! `#[cfg(feature)]` changing what the *hardware* answers, leaving the decoder
//! and everything downstream of it shipped code.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::Duration;

use super::fwvars;
use super::qemu::{self, BootOptions, QemuInstance};
use super::serial;
use super::volumes::{self, Entry};

/// What the host sets the emulated RTC to, and the same instant in seconds.
///
/// A date this century, so the machine is self-consistent: QEMU sets the clock
/// registers and leaves the century register alone at the 20 firmware wrote, and
/// those two agree only for the 2000s. Well inside FAT's range, whose last
/// representable day is 2107-12-31, because the file this boot writes has to
/// carry the instant as its own timestamp and a clamp would hide a wrong one.
const RTC_BASE: &str = "2033-03-07T09:14:25";
const RTC_BASE_SECS: i64 = 1_993_799_665;
/// What a file named for that instant begins with. The date and not the time,
/// because the seconds move on while the machine boots and [`after_the_base`]
/// is what bounds that — the timestamp inside the entry is where this is
/// checked to the second.
const RTC_BASE_DATE: &str = "2033-03-07-";

/// Whether `secs` past [`RTC_BASE`] is a time this guest's clock can have read:
/// not before the instant the host staged, and not after the RTC — which runs
/// from that instant at the host's own pace from the moment QEMU starts — had
/// got to by the time the boot was read back, `lived` after the launch. Both
/// ends are causality and neither is a margin: a slower host only widens the
/// second, and a kernel that got the century or a zone wrong is out by years or
/// hours.
fn after_the_base(secs: i64, lived: Duration) -> bool {
    (0..=lived.as_secs_f64().ceil() as i64).contains(&secs)
}

/// What [`boot_and_read`] makes the guest print into the window between the
/// ready marker and the first test it runs.
///
/// Distinctive enough that nothing else on a console could be it, and short
/// enough to be one `write`.
const WINDOW_MARKER: &str = "between-tests-window-is-captured";

/// How many logs `/system/bin/logd`'s `MAX_LOG_FILES` keeps. Mirrored rather than shared,
/// so moving the kernel's bound without looking at this fails here rather than
/// quietly weakening the gate.
pub const MAX_LOG_FILES: usize = 16;

/// The log files this module's kernel wrote or was given, oldest first.
fn logs(entries: &[Entry]) -> Vec<&Entry> {
    entries.iter().filter(|e| toyos_build::bootlog::is_logd_file(&e.name)).collect()
}

fn names(entries: &[&Entry]) -> String {
    entries.iter().map(|e| e.name.as_str()).collect::<Vec<_>>().join(", ")
}

/// What `wall_clock_now` printed for `SYS_CLOCK_EPOCH`.
fn probed_epoch(log: &str) -> Option<i64> {
    let line = log.lines().find(|l| l.contains("wall-clock: epoch="))?;
    let rest = line.split("epoch=").nth(1)?;
    rest.split_whitespace().next()?.parse().ok()
}

fn clock_lines(log: &str) -> String {
    let lines: Vec<&str> = log
        .lines()
        .filter(|l| {
            l.contains("clock:") || l.contains("logd:") || l.contains("RTC") || l.contains("rtc")
        })
        .collect();
    if lines.is_empty() {
        return format!("the guest said nothing about its clock at all\n{log}");
    }
    format!("what it said:\n{}", lines.join("\n"))
}

/// A boot with the wall clock staged, returning the log volume afterwards.
///
/// Metal-sim, because that is the machine shape that gets flashed and the one
/// whose whole reason for having a log on a stick is that it has no serial
/// port. The guest is shut down before the volume is read: the claims here are
/// about the *name* and the timestamp of a file, both of which are decided when
/// the sink installs, so unlike `kernel_log_file` there is nothing to catch
/// mid-run.
fn boot_and_read(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
    image_name: &str,
    params: &'static [&'static str],
    stage: &[(String, Vec<u8>)],
    firmware_vars: Option<PathBuf>,
) -> Result<(Vec<Entry>, String, Duration), String> {
    let image_path = super::lane::dir().join(image_name);
    let mut image = qemu::build_boot_image(test_config, c_bins, rust_bins, params);
    std::fs::write(&image_path, &image).map_err(|e| format!("write the boot image: {e}"))?;
    let (start, len) = volumes::log_extent(&image, &image_path)?;

    if !stage.is_empty() {
        volumes::stage_files(&mut image[start..start + len], stage)?;
        std::fs::write(&image_path, &image).map_err(|e| format!("rewrite the boot image: {e}"))?;
    }

    // Before the launch, so the RTC the guest reads has run no longer than this.
    let launched = std::time::Instant::now();
    let mut qemu = QemuInstance::boot_with_options(
        test_config,
        c_bins,
        rust_bins,
        BootOptions {
            profile: qemu::Profile::Metal,
            boot_image: Some(qemu::Staged::Written(image_path.clone())),
            kernel_params: params,
            rtc_base: Some(RTC_BASE),
            firmware_vars,
            ..Default::default()
        },
    );
    let mut log = qemu.boot_log().to_string();
    serial::Serial::named("boot console", log.as_str()).must_be_clean()?;
    // **A line printed into the window between the ready marker and the first
    // test, staged so that losing it is a red rather than a flake.**
    //
    // `logd` writes its retention line, creates this boot's file — a device
    // write, milliseconds — and then writes its identity line; the window used
    // to close between the two and the first line was dropped by the harness
    // with nothing saying so. `run echo` is the smallest thing that lands in
    // that window on purpose: the guest's runner reads commands in order, so
    // this whole exchange strictly precedes the probe's `===TEST_START===` and
    // every line of it arrives while the next `run_test` is waiting for its own
    // marker. `TestResult::before` is what keeps it.
    writeln!(qemu.stdin_mut(), "run echo {WINDOW_MARKER}")
        .map_err(|e| format!("stage the between-tests window: {e}"))?;
    qemu.flush_stdin();
    let probe = qemu.run_test("test_rs_wall_clock_now", Duration::from_secs(30));
    log.push_str(&probe.before);
    log.push_str(&probe.stdout);
    if !log.contains(WINDOW_MARKER) {
        return Err(format!(
            "the guest printed {WINDOW_MARKER} between the ready marker and the probe's start and \
             this capture does not carry it — the window between two tests is being dropped, which \
             is how a daemon's startup line goes missing from a boot nothing else is wrong \
             with\nbefore:\n{}\nstdout:\n{}",
            probe.before, probe.stdout
        ));
    }
    writeln!(qemu.stdin_mut(), "run shutdown").expect("write to QEMU stdin");
    qemu.flush_stdin();
    log.push_str(&qemu.drain_serial(Duration::from_secs(20)));
    drop(qemu);
    for bad in ["PANIC:", "panicked at"] {
        if log.contains(bad) {
            return Err(format!("{bad:?} on the way down\n{log}"));
        }
    }

    let after = std::fs::read(&image_path).map_err(|e| format!("read the image back: {e}"))?;
    if start + len > after.len() {
        return Err(format!("the image shrank to {} bytes", after.len()));
    }
    let entries = volumes::root_entries(&after[start..start + len])?;
    let _ = std::fs::remove_file(&image_path);
    Ok((entries, log, launched.elapsed()))
}

/// `PcatRealTimeClockRuntimeDxe`'s `FILE_GUID`, `378D7B65-8DA9-4773-B6E4-A47826A833E1`,
/// in the byte order `EFI_GUID` stores: the vendor of the `RTC` variable its
/// `PcRtcInit` reads `EFI_TIME::TimeZone` out of (edk2
/// `PcAtChipsetPkg/PcatRealTimeClockRuntimeDxe/PcRtc.c`).
const PC_RTC_VENDOR: [u8; 16] =
    [0x65, 0x7b, 0x8d, 0x37, 0xa9, 0x8d, 0x73, 0x47, 0xb6, 0xe4, 0xa4, 0x78, 0x26, 0xa8, 0x33, 0xe1];
/// `EFI_VARIABLE_NON_VOLATILE | BOOTSERVICE_ACCESS | RUNTIME_ACCESS`, what
/// `PcRtcSetTime` stores the zone with.
const PC_RTC_ATTRIBUTES: u32 = 0x7;
/// UTC+2 in `EFI_TIME::TimeZone`, whose relation is `Localtime = UTC - TimeZone`.
const FIRMWARE_ZONE_MINUTES: i16 = -120;

/// How far `h:m:s` is past the staged instant's own time of day; the base is
/// far enough from midnight that no boot crosses one.
fn past_the_base(h: &str, m: &str, s: &str) -> Option<i64> {
    let [h, m, s] = [h, m, s].map(|field| field.parse::<i64>().ok());
    Some(h? * 3_600 + m? * 60 + s? - RTC_BASE_SECS.rem_euclid(86_400))
}

/// What `wall_clock_now` printed for `SYS_CLOCK_REALTIME`, past the base.
fn probed_realtime(log: &str) -> Option<i64> {
    let line = log.lines().find(|l| l.contains("wall-clock: epoch="))?;
    let hms = line.split("realtime=").nth(1)?.split_whitespace().next()?;
    let [h, m, s] = hms.split(':').collect::<Vec<_>>()[..] else { return None };
    past_the_base(h, m, s)
}

pub fn rtc_is_utc(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    let vars = super::lane::dir().join("wall-clock-utc-vars.fd");
    toyos_build::firmware::of(qemu::Profile::Metal.arch())?.fresh_vars(&vars)?;
    let zone = u32::from(FIRMWARE_ZONE_MINUTES as u16).to_le_bytes();
    fwvars::plant(&vars, &PC_RTC_VENDOR, "RTC", PC_RTC_ATTRIBUTES, &zone)?;
    let booted =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-utc.img", &[], &[], Some(vars.clone()));
    let _ = std::fs::remove_file(&vars);
    let (entries, log, lived) = booted?;
    let logs = logs(&entries);

    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    let named = only.name.strip_prefix(RTC_BASE_DATE).and_then(|hms| hms.strip_suffix(".log")).and_then(|hms| {
        let (h, ms) = hms.split_at_checked(2)?;
        let (m, s) = ms.split_at_checked(2)?;
        past_the_base(h, m, s)
    });
    if !named.is_some_and(|drift| after_the_base(drift, lived)) {
        return Err(format!(
            "the log is {} and the host staged {RTC_BASE}\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    let stamp_drift = only.modified - RTC_BASE_SECS;
    if !after_the_base(stamp_drift, lived) {
        return Err(format!(
            "this boot's FAT timestamp is {stamp_drift}s from the staged instant\n{}",
            clock_lines(&log)
        ));
    }

    let Some(epoch) = probed_epoch(&log) else {
        return Err(format!(
            "the guest never printed what `SYS_CLOCK_EPOCH` answered\n{}",
            clock_lines(&log)
        ));
    };
    let drift = epoch - RTC_BASE_SECS;
    if !after_the_base(drift, lived) {
        return Err(format!(
            "`SYS_CLOCK_EPOCH` answered {epoch}, {drift}s from the staged instant\n{}",
            clock_lines(&log)
        ));
    }
    let Some(realtime_drift) = probed_realtime(&log) else {
        return Err(format!(
            "the guest never printed what `SYS_CLOCK_REALTIME` answered\n{}",
            clock_lines(&log)
        ));
    };
    if !after_the_base(realtime_drift, lived) {
        return Err(format!(
            "`SYS_CLOCK_REALTIME` answered a time of day {realtime_drift}s from the staged \
             instant's\n{}",
            clock_lines(&log)
        ));
    }
    eprintln!(
        "  [clock] with firmware naming {FIRMWARE_ZONE_MINUTES} minutes, {}, its FAT stamp, epoch \
         {epoch} and the time of day sit on the staged instant",
        only.name
    );
    Ok(())
}

/// A machine whose clock will not answer still boots, still logs, and says so
/// in the name of the file it writes.
pub fn undated(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
    image_name: &str,
    params: &'static [&'static str],
    because: &str,
) -> Result<(), String> {
    let (entries, log, _) =
        boot_and_read(test_config, c_bins, rust_bins, image_name, params, &[], None)?;
    let logs = logs(&entries);

    // The refusal, by name and with its reason. A kernel that silently took
    // some other number for the time would produce a dated file and no line.
    if !log.contains("clock: this machine will not say what time it is") || !log.contains(because) {
        return Err(format!(
            "with {params:?} the kernel never refused the clock for {because:?}\n{}",
            clock_lines(&log)
        ));
    }
    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    if only.name != "unknown-00.log" {
        return Err(format!(
            "with {params:?} this boot's log is {}, which claims a time the machine never gave \
             it\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    // The boot has to have *finished* — a clock that refuses must not cost the
    // machine anything else — and the file has to carry it.
    if !log.contains("Boot: complete") {
        return Err(format!("with {params:?} the boot never completed\n{log}"));
    }
    // Userland is told the same thing the kernel knows. A syscall answering
    // 1970 here is the defect this whole shape exists to make impossible: the
    // caller cannot tell it from a machine that really is at the epoch.
    if !log.contains("wall-clock: no epoch") {
        return Err(format!(
            "with {params:?} the clock syscalls did not refuse a process the way the kernel \
             refused itself\n{}",
            clock_lines(&log)
        ));
    }
    if only.len == 0 {
        return Err(format!("with {params:?} {} is on the volume and empty", only.name));
    }
    eprintln!(
        "  [clock] {params:?}: refused by name, {} carries {} bytes, boot complete",
        only.name, only.len
    );
    Ok(())
}

/// A FADT that names no century register: the machine still has a clock, and
/// the year comes from two digits and the stated assumption.
///
/// The old code could not express this state at all — it read CMOS 0x32
/// whatever the FADT said and took anything non-zero as a century — so the
/// assertion is that the *table's* answer is what decides, and that answering
/// "none" costs the machine its century rather than its clock.
pub fn no_century(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    // Both, and the second is what gives this teeth. With the register left as
    // the machine has it, honouring the FADT's "none" and ignoring it produce
    // the same year — 2000 plus two digits, and a register holding 20 — so a
    // kernel that read a hardcoded 0x32 would pass. Staging the register at the
    // *next* century separates them: honouring the table gives 2033 and
    // ignoring it gives 2133.
    const PARAMS: &[&str] = &["rtc-no-century", "rtc-century-next"];
    let (entries, log, _) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-no-century.img", PARAMS, &[], None)?;
    let logs = logs(&entries);

    if !log.contains("ACPI: the FADT names no RTC century register") {
        return Err(format!(
            "the kernel never said the FADT named no century register\n{}",
            clock_lines(&log)
        ));
    }
    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    if !only.name.starts_with(RTC_BASE_DATE) {
        return Err(format!(
            "with no century register this boot's log is {}, and two digits plus 2000 is \
             {RTC_BASE_DATE} — a name in 2133 means the register was read anyway\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    eprintln!(
        "  [clock] no century register: {}, from two digits and 2000, with the register itself \
         staged a century away",
        only.name
    );
    Ok(())
}

/// The century register's *contents* are what widen the year.
///
/// The one thing `-rtc base=` cannot stage, so the register answers 0x21 and
/// nothing else changes: same clock registers, same FADT, same decoder. A
/// kernel that ignored the register — or read a fixed 2000 — puts this boot in
/// 2033 like every other one here, and the file name is where that shows.
pub fn century_from_the_register(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    const PARAMS: &[&str] = &["rtc-century-next"];
    let (entries, log, _) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-century.img", PARAMS, &[], None)?;
    let logs = logs(&entries);

    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    // 2133 and not 2033: the same two year digits under the next century. The
    // day and time are the host's, so only the century moved.
    if !only.name.starts_with("2133-03-07-") {
        return Err(format!(
            "with the century register answering 0x21 this boot's log is {}, and the year the \
             registers describe is 2133-03-07\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    eprintln!("  [clock] century register 0x21: {}, a century past the staged clock", only.name);
    Ok(())
}

/// Where [`file_mtime_survives_a_reboot`] writes, on DATA: the one volume a
/// file outlives its boot on.
const MTIME_PATH: &str = "/home/file-mtime.bin";

/// The second boot's RTC, a day past [`RTC_BASE`]: a stamp taken again at the
/// mount or the open would carry this day, so an unchanged one was carried.
const RTC_NEXT_DAY: &str = "2033-03-08T09:14:25";

/// What `file_mtime` printed for [`MTIME_PATH`], in nanoseconds.
fn printed_mtime(result: &qemu::TestResult) -> Result<u64, String> {
    let head = format!("file-mtime: {MTIME_PATH} mtime=");
    result
        .stdout
        .lines()
        .find_map(|l| l.trim().strip_prefix(head.as_str()))
        .and_then(|n| n.parse().ok())
        .ok_or_else(|| {
            format!(
                "`{}` printed no {head:?} line (exit {:?})\n{}{}{}",
                result.name, result.exit_code, result.before, result.stdout, result.serial
            )
        })
}

/// One boot of the image `data` carries DATA on, with the RTC at `rtc_base`,
/// running `file_mtime <mode> MTIME_PATH`, then shut down.
fn mtime_boot(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
    data: &Path,
    rtc_base: &'static str,
    mode: &str,
) -> Result<(u64, Duration), String> {
    // Before the launch, so the RTC the guest reads has run no longer than this.
    let launched = std::time::Instant::now();
    let mut qemu = QemuInstance::boot_with_options(
        test_config,
        c_bins,
        rust_bins,
        BootOptions {
            nvme_image: Some(data.to_path_buf()),
            rtc_base: Some(rtc_base),
            ..Default::default()
        },
    );
    let boot = qemu.boot_log().to_string();
    if boot.contains(super::storage::IN_MEMORY) {
        return Err(format!("/home fell back to memory, so no file of it outlives the boot:\n{boot}"));
    }
    let result = qemu.run_test(&format!("test_rs_file_mtime {mode} {MTIME_PATH}"), Duration::from_secs(50));
    let printed = printed_mtime(&result);
    writeln!(qemu.stdin_mut(), "run shutdown").expect("write to QEMU stdin");
    qemu.flush_stdin();
    let tail = qemu.drain_serial(Duration::from_secs(20));
    drop(qemu);
    for bad in ["PANIC:", "panicked at"] {
        if tail.contains(bad) {
            return Err(format!("{bad:?} on the way down\n{tail}"));
        }
    }
    if result.exit_code != Some(0) {
        return Err(format!(
            "`file_mtime {mode}` failed:\n{}\nkernel log while it ran:\n{}{}",
            result.stdout, result.before, result.serial
        ));
    }
    printed.map(|n| (n, launched.elapsed()))
}

/// A file's mtime is the wall clock at its write, and a reboot carries it
/// unchanged.
///
/// The oracle is the instant the host staged with `-rtc base=`: the guest's
/// stamp for a file on DATA lies within [`after_the_base`] of it, the
/// DATA volume read off the image by the host's own `bcachefs` reader holds
/// that same stamp, and a second boot with the clock a day on reads it back
/// unchanged. A stamp since boot is decades short of the instant.
pub fn file_mtime_survives_a_reboot(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    const NANOS_PER_SEC: u64 = 1_000_000_000;

    let data = super::lane::dir().join("file-mtime-data.img");
    toyos_build::build::create_sparse(&data, qemu::NVME_SMALL);

    let (written, lived) = mtime_boot(test_config, c_bins, rust_bins, &data, RTC_BASE, "write")?;
    let drift = (written / NANOS_PER_SEC) as i64 - RTC_BASE_SECS;
    if !after_the_base(drift, lived) {
        return Err(format!(
            "{MTIME_PATH} is stamped {written} ns, {drift} s from the {RTC_BASE} the host set the \
             RTC to"
        ));
    }

    let io = super::storage::FileBlocks::open(&data)?;
    let fs = bcachefs::Mounted::<_, bcachefs::ReadOnly>::open(io)
        .map_err(|e| format!("the DATA volume does not mount on the host: {e:?}"))?;
    let on_device = fs
        .file_mtime(MTIME_PATH.trim_start_matches('/'))
        .map_err(|e| format!("reading {MTIME_PATH}'s mtime off the image: {e:?}"))?;
    drop(fs);
    if on_device != Some(written) {
        return Err(format!(
            "the guest read {written} ns for {MTIME_PATH} and the device holds {on_device:?}"
        ));
    }

    let (read, _) = mtime_boot(test_config, c_bins, rust_bins, &data, RTC_NEXT_DAY, "read")?;
    if read != written {
        return Err(format!(
            "{MTIME_PATH} was stamped {written} ns and reads {read} ns after a reboot with the RTC \
             at {RTC_NEXT_DAY}"
        ));
    }
    let _ = std::fs::remove_file(&data);
    eprintln!(
        "  [clock] {MTIME_PATH} stamped {drift} s past the staged RTC, the same {written} ns on \
         the device and after a reboot a day on"
    );
    Ok(())
}

/// On a machine whose RTC never answered, a file's mtime on `/tmp` or on fsd's
/// `/home` is undated — 0, which std reports as an error — and never 1970 plus
/// the boot's uptime.
pub fn file_mtime_undated(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    const SAID: [&str; 2] =
        ["file-mtime: /tmp/file-mtime-undated is undated", "file-mtime: /home/file-mtime-undated is undated"];
    let mut qemu = QemuInstance::boot_with_options(
        test_config,
        c_bins,
        rust_bins,
        BootOptions { kernel_params: &["rtc-dead"], ..Default::default() },
    );
    let boot = qemu.boot_log().to_string();
    if !boot.contains("clock: this machine will not say what time it is") {
        return Err(format!(
            "with rtc-dead armed the kernel never refused the clock\n{}",
            clock_lines(&boot)
        ));
    }
    let result = qemu.run_test("test_rs_file_mtime undated", Duration::from_secs(29));
    writeln!(qemu.stdin_mut(), "run shutdown").expect("write to QEMU stdin");
    qemu.flush_stdin();
    let tail = qemu.drain_serial(Duration::from_secs(20));
    drop(qemu);
    for bad in ["PANIC:", "panicked at"] {
        if tail.contains(bad) {
            return Err(format!("{bad:?} on the way down\n{tail}"));
        }
    }
    if result.exit_code != Some(0) || !SAID.iter().all(|said| result.stdout.contains(said)) {
        return Err(format!(
            "`file_mtime undated` exited {:?}:\n{}\nkernel log while it ran:\n{}{}",
            result.exit_code, result.stdout, result.before, result.serial
        ));
    }
    eprintln!("  [clock] rtc-dead: a file written in /tmp or /home is undated");
    Ok(())
}
