//! What the machine thinks the time is, and what it does when it cannot tell.
//!
//! The wall clock is one of the few devices the *host* can set, which is what
//! makes this checkable from outside the guest at all: `-rtc base=` puts a
//! known instant in the emulated CMOS before the machine starts, so the name
//! and the timestamp of the file the guest writes are both known before there
//! is a guest. The volume's verdicts are read off the disk image the device
//! received; the clock *syscalls* reach no disk, so what the guest printed for
//! those is judged against that same staged instant and nothing it derived.
//!
//! # What only an actuator can stage
//!
//! Four states of the clock, and the host can produce none of them: QEMU has no
//! switch that removes or wedges the mc146818, its RTC always presents the
//! guest a coherent register set, the FADT a guest reads is generated by QEMU
//! and always names the century register at 0x32, and `-rtc base=` sets every
//! digit of the date **except** the century. That last one is measured rather
//! than assumed: a guest booted with `base=2101-06-05` reads century 20 and
//! year 01 out of its own registers and correctly reports 2001, because QEMU
//! maintains the clock registers and leaves CMOS 0x32 at whatever firmware last
//! wrote there. So a staged year cannot distinguish a kernel that reads the
//! century register from one that assumes 2000 — [`no_century`] and
//! [`century_from_the_register`] are the two halves that can, and each is a
//! `#[cfg(feature)]` changing what the *hardware* answers, leaving the decoder
//! and everything downstream of it shipped code.

use std::io::Write;
use std::path::Path;
use std::time::Duration;

use super::qemu::{self, BootOptions, QemuInstance};
use super::serial;
use super::volumes::{self, Entry};

/// What the host sets the emulated RTC to, and the same instant in seconds.
///
/// A date this century, so the machine is self-consistent: QEMU sets the clock
/// registers and leaves the century register alone at the 20 firmware wrote, and
/// those two agree only for the 2000s. Well inside FAT's range, whose last
/// representable day is 2107-12-31, because the file this boot writes has to
/// carry the instant as its own timestamp and a clamp would hide a wrong one.
const RTC_BASE: &str = "2033-03-07T09:14:25";
const RTC_BASE_SECS: i64 = 1_993_799_665;
/// What a file named for that instant begins with. The date and not the time,
/// because the seconds move on while the machine boots and
/// [`MAX_BOOT_DRIFT_SECS`] is what bounds that — the timestamp inside the entry
/// is where this is checked to the second.
const RTC_BASE_DATE: &str = "2033-03-07-";

/// How far past [`RTC_BASE`] the guest may have got by the time it names its
/// log file.
///
/// The guest's clock runs from the base at host speed, so this is a boot's own
/// wall-clock duration and nothing else — a machine that reaches its log sink
/// in under a second on a quiet host, and in a good deal more on a busy one.
/// Five minutes is three orders of magnitude above the former, which keeps this
/// from being a wall-clock margin the way the serial-tail tests' verdicts are:
/// nothing in the phase can slow a boot by that much, and a kernel that got the
/// century wrong is out by a hundred years rather than by seconds.
const MAX_BOOT_DRIFT_SECS: i64 = 300;

/// What [`boot_and_read`] makes the guest print into the window between the
/// ready marker and the first test it runs.
///
/// Distinctive enough that nothing else on a console could be it, and short
/// enough to be one `write`.
const WINDOW_MARKER: &str = "between-tests-window-is-captured";

/// How many logs `/system/bin/logd`'s `MAX_LOG_FILES` keeps. Mirrored rather than shared,
/// so moving the kernel's bound without looking at this fails here rather than
/// quietly weakening the gate.
pub const MAX_LOG_FILES: usize = 16;

/// The name of the boot the guest must delete, and the ones it must not.
///
/// Sixteen staged files, so the volume is exactly at the bound before the guest
/// starts and this boot's own file is the one that puts it over. They are dated
/// well before [`RTC_BASE`], so the one that has to go is unambiguous — and
/// they are *not* consecutive days, so an implementation deleting "the first one
/// it listed" or "the lowest index" rather than the oldest lands on a different
/// file than the one asserted.
fn staged_logs() -> Vec<(String, Vec<u8>)> {
    (0..MAX_LOG_FILES)
        .map(|i| {
            let name = format!("2019-12-{:02}-120000.log", 1 + i * 2);
            let body = format!("staged by the host as boot {i}\n").into_bytes();
            (name, body)
        })
        .collect()
}

/// The log files this module's kernel wrote or was given, oldest first.
fn logs(entries: &[Entry]) -> Vec<&Entry> {
    entries.iter().filter(|e| e.name.ends_with(".log")).collect()
}

fn names(entries: &[&Entry]) -> String {
    entries.iter().map(|e| e.name.as_str()).collect::<Vec<_>>().join(", ")
}

/// The clock lines from a boot log, for a failure message that says why.
/// What `wall_clock_now` printed for `SYS_CLOCK_EPOCH`.
fn probed_epoch(log: &str) -> Option<i64> {
    let line = log.lines().find(|l| l.contains("wall-clock: epoch="))?;
    let rest = line.split("epoch=").nth(1)?;
    rest.split_whitespace().next()?.parse().ok()
}

/// What the same probe printed for `std`'s `SystemTime::now`.
fn probed_std_epoch(log: &str) -> Option<i64> {
    let line = log.lines().find(|l| l.contains("wall-clock: std_epoch="))?;
    let rest = line.split("std_epoch=").nth(1)?;
    rest.split_whitespace().next()?.parse().ok()
}

fn clock_lines(log: &str) -> String {
    let lines: Vec<&str> = log
        .lines()
        .filter(|l| {
            l.contains("clock:") || l.contains("logd:") || l.contains("RTC") || l.contains("rtc")
        })
        .collect();
    if lines.is_empty() {
        return format!("the guest said nothing about its clock at all\n{log}");
    }
    format!("what it said:\n{}", lines.join("\n"))
}

/// A boot with the wall clock staged, returning the log volume afterwards.
///
/// Metal-sim, because that is the machine shape that gets flashed and the one
/// whose whole reason for having a log on a stick is that it has no serial
/// port. The guest is shut down before the volume is read: the claims here are
/// about the *name* and the timestamp of a file, both of which are decided when
/// the sink installs, so unlike `kernel_log_file` there is nothing to catch
/// mid-run.
fn boot_and_read(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
    image_name: &str,
    params: &'static [&'static str],
    stage: &[(String, Vec<u8>)],
) -> Result<(Vec<Entry>, String), String> {
    let image_path = super::lane::dir().join(image_name);
    let mut image = qemu::build_boot_image(test_config, c_bins, rust_bins, params);
    std::fs::write(&image_path, &image).map_err(|e| format!("write the boot image: {e}"))?;
    let (start, len) = volumes::log_extent(&image, &image_path)?;

    if !stage.is_empty() {
        volumes::stage_files(&mut image[start..start + len], stage)?;
        std::fs::write(&image_path, &image).map_err(|e| format!("rewrite the boot image: {e}"))?;
    }

    let mut qemu = QemuInstance::boot_with_options(
        test_config,
        c_bins,
        rust_bins,
        BootOptions {
            profile: qemu::Profile::Metal,
            boot_image: Some(image_path.clone()),
            kernel_params: params,
            rtc_base: Some(RTC_BASE),
            ..Default::default()
        },
    );
    let mut log = qemu.boot_log().to_string();
    serial::Serial::named("boot console", log.as_str()).must_be_clean()?;
    // **A line printed into the window between the ready marker and the first
    // test, staged so that losing it is a red rather than a flake.**
    //
    // `logd` writes its retention line, creates this boot's file — a device
    // write, milliseconds — and then writes its identity line; the window used
    // to close between the two and the first line was dropped by the harness
    // with nothing saying so. `run echo` is the smallest thing that lands in
    // that window on purpose: the guest's runner reads commands in order, so
    // this whole exchange strictly precedes the probe's `===TEST_START===` and
    // every line of it arrives while the next `run_test` is waiting for its own
    // marker. `TestResult::before` is what keeps it.
    writeln!(qemu.stdin_mut(), "run echo {WINDOW_MARKER}")
        .map_err(|e| format!("stage the between-tests window: {e}"))?;
    qemu.flush_stdin();
    // What the two clock syscalls answer, which nothing on the volume can show:
    // the file name is local time and `SYS_CLOCK_EPOCH` serves UTC.
    let probe = qemu.run_test("test_rs_wall_clock_now", Duration::from_secs(30));
    log.push_str(&probe.before);
    log.push_str(&probe.stdout);
    if !log.contains(WINDOW_MARKER) {
        return Err(format!(
            "the guest printed {WINDOW_MARKER} between the ready marker and the probe's start and \
             this capture does not carry it — the window between two tests is being dropped, which \
             is how a daemon's startup line goes missing from a boot nothing else is wrong \
             with\nbefore:\n{}\nstdout:\n{}",
            probe.before, probe.stdout
        ));
    }
    writeln!(qemu.stdin_mut(), "run shutdown").expect("write to QEMU stdin");
    qemu.flush_stdin();
    log.push_str(&qemu.drain_serial(Duration::from_secs(20)));
    drop(qemu);
    for bad in ["PANIC:", "panicked at"] {
        if log.contains(bad) {
            return Err(format!("{bad:?} on the way down\n{log}"));
        }
    }

    let after = std::fs::read(&image_path).map_err(|e| format!("read the image back: {e}"))?;
    if start + len > after.len() {
        return Err(format!("the image shrank to {} bytes", after.len()));
    }
    let entries = volumes::root_entries(&after[start..start + len])?;
    let _ = std::fs::remove_file(&image_path);
    Ok((entries, log))
}

/// One file per boot, named and stamped from the wall clock, with the oldest
/// deleted once the volume is at its bound.
pub fn wall_clock_file(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    let staged = staged_logs();
    let (entries, log) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-boot.img", &[], &staged)?;
    let logs = logs(&entries);

    // The bound, on the volume rather than in the guest's account of it.
    if logs.len() != MAX_LOG_FILES {
        return Err(format!(
            "the volume holds {} logs, not the {MAX_LOG_FILES} the bound allows: {}\n{}",
            logs.len(),
            names(&logs),
            clock_lines(&log)
        ));
    }

    // The oldest staged file and no other. `staged_logs` dates them two days
    // apart, so deleting by list order or by index would take a different one.
    let oldest = &staged[0].0;
    if logs.iter().any(|e| &e.name == oldest) {
        return Err(format!(
            "the oldest log {oldest} is still on the volume, so the bound was met by deleting \
             something else: {}",
            names(&logs)
        ));
    }
    for (name, _) in &staged[1..] {
        if !logs.iter().any(|e| &e.name == name) {
            return Err(format!(
                "{name} was deleted and it is not the oldest: {}\n{}",
                names(&logs),
                clock_lines(&log)
            ));
        }
    }
    if !log.contains(&format!("/log/{oldest} was deleted")) {
        return Err(format!(
            "nothing in the log names {oldest} as the file that was deleted to make room\n{}",
            clock_lines(&log)
        ));
    }

    // This boot's own file: named for the staged instant, which needs the
    // century register to come out as 2101 rather than 2001.
    let Some(mine) = logs.iter().find(|e| e.name.starts_with(RTC_BASE_DATE)) else {
        return Err(format!(
            "no log named for the day the host staged ({RTC_BASE_DATE}*): {}\n{}",
            names(&logs),
            clock_lines(&log)
        ));
    };
    let drift = mine.modified - RTC_BASE_SECS;
    if !(0..=MAX_BOOT_DRIFT_SECS).contains(&drift) {
        return Err(format!(
            "{} carries a timestamp {drift}s from the {RTC_BASE} the host set, outside \
             0..={MAX_BOOT_DRIFT_SECS}\n{}",
            mine.name,
            clock_lines(&log)
        ));
    }
    if mine.len == 0 {
        return Err(format!("{} is on the volume and empty", mine.name));
    }

    // The other end of the same instant. Firmware named no zone on this
    // machine — OVMF ships `EFI_UNSPECIFIED_TIMEZONE` — so the kernel takes the
    // RTC as UTC and the epoch syscall must answer the staged instant itself.
    // A kernel serving 1970, or serving local time shifted by a zone it
    // invented, lands outside this window.
    let Some(epoch) = probed_epoch(&log) else {
        return Err(format!(
            "the guest never printed what `SYS_CLOCK_EPOCH` answered\n{}",
            clock_lines(&log)
        ));
    };
    let epoch_drift = epoch - RTC_BASE_SECS;
    if !(0..=MAX_BOOT_DRIFT_SECS).contains(&epoch_drift) {
        return Err(format!(
            "`SYS_CLOCK_EPOCH` answered {epoch}, {epoch_drift}s from the {RTC_BASE} the host set \
             and outside 0..={MAX_BOOT_DRIFT_SECS}\n{}",
            clock_lines(&log)
        ));
    }

    // Judged against `RTC_BASE` and not against the syscall above, so a std
    // agreeing with a wrong kernel still lands outside this window.
    let Some(std_epoch) = probed_std_epoch(&log) else {
        return Err(format!(
            "the guest never printed what std's `SystemTime::now` answered\n{}",
            clock_lines(&log)
        ));
    };
    let std_drift = std_epoch - RTC_BASE_SECS;
    if !(0..=MAX_BOOT_DRIFT_SECS).contains(&std_drift) {
        return Err(format!(
            "std's `SystemTime::now` answered {std_epoch}, {std_drift}s from the {RTC_BASE} the \
             host set and outside 0..={MAX_BOOT_DRIFT_SECS}. A std that never asks the kernel \
             answers the epoch, which is {}s out\n{}",
            -RTC_BASE_SECS,
            clock_lines(&log)
        ));
    }

    eprintln!(
        "  [clock] {} carries {} bytes, stamped {drift}s after the {RTC_BASE} the host set, epoch \
         {epoch_drift}s after it and std {std_drift}s after it; {} deleted for the \
         {MAX_LOG_FILES}-log bound",
        mine.name, mine.len, oldest
    );
    Ok(())
}

/// A firmware-named zone separates local time from UTC, in the direction UEFI
/// defines.
///
/// The clock the RTC reads is local by firmware's account, so the file name and
/// every FAT stamp stay on the staged instant; only `SYS_CLOCK_EPOCH` moves.
/// UEFI's relation is `Localtime = UTC - TimeZone`, so the two hours east this
/// stages report -120 and UTC comes out *behind* the RTC — the sign that a
/// reader of the field gets backwards, and the one that would put a dual-booted
/// laptop four hours out rather than two.
pub fn zone_from_firmware(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    const PARAMS: &[&str] = &["rtc-zone-east"];
    /// What `clock::init_wall` stages, in seconds: two hours east of UTC.
    const OFFSET_SECS: i64 = -120 * 60;

    let (entries, log) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-zone.img", PARAMS, &[])?;
    let logs = logs(&entries);

    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    // Unmoved: FAT stores local time by specification, and so does the name.
    if !only.name.starts_with(RTC_BASE_DATE) {
        return Err(format!(
            "a zone moved this boot's *local* time: the log is {} and the host staged \
             {RTC_BASE}\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    let stamp_drift = only.modified - RTC_BASE_SECS;
    if !(0..=MAX_BOOT_DRIFT_SECS).contains(&stamp_drift) {
        return Err(format!(
            "a zone moved this boot's FAT timestamp by {stamp_drift}s, and FAT stores local time"
        ));
    }

    let Some(epoch) = probed_epoch(&log) else {
        return Err(format!(
            "the guest never printed what `SYS_CLOCK_EPOCH` answered\n{}",
            clock_lines(&log)
        ));
    };
    let drift = epoch - (RTC_BASE_SECS + OFFSET_SECS);
    if !(0..=MAX_BOOT_DRIFT_SECS).contains(&drift) {
        let unshifted = epoch - RTC_BASE_SECS;
        return Err(format!(
            "with firmware naming -120 minutes, `SYS_CLOCK_EPOCH` answered {epoch}: {drift}s from \
             the UTC that implies, and {unshifted}s from the RTC's own reading. Zero for the \
             second means the offset was dropped; {}s means its sign is inverted\n{}",
            -OFFSET_SECS * 2,
            clock_lines(&log)
        ));
    }
    eprintln!(
        "  [clock] firmware naming -120 minutes: {} keeps local time, epoch is {}s behind it",
        only.name, -OFFSET_SECS
    );
    Ok(())
}

/// A machine whose clock will not answer still boots, still logs, and says so
/// in the name of the file it writes.
pub fn undated(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
    image_name: &str,
    params: &'static [&'static str],
    because: &str,
) -> Result<(), String> {
    let (entries, log) = boot_and_read(test_config, c_bins, rust_bins, image_name, params, &[])?;
    let logs = logs(&entries);

    // The refusal, by name and with its reason. A kernel that silently took
    // some other number for the time would produce a dated file and no line.
    if !log.contains("clock: this machine will not say what time it is") || !log.contains(because) {
        return Err(format!(
            "with {params:?} the kernel never refused the clock for {because:?}\n{}",
            clock_lines(&log)
        ));
    }
    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    if only.name != "unknown-00.log" {
        return Err(format!(
            "with {params:?} this boot's log is {}, which claims a time the machine never gave \
             it\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    // The boot has to have *finished* — a clock that refuses must not cost the
    // machine anything else — and the file has to carry it.
    if !log.contains("Boot: complete") {
        return Err(format!("with {params:?} the boot never completed\n{log}"));
    }
    // Userland is told the same thing the kernel knows. A syscall answering
    // 1970 here is the defect this whole shape exists to make impossible: the
    // caller cannot tell it from a machine that really is at the epoch.
    if !log.contains("wall-clock: no epoch") {
        return Err(format!(
            "with {params:?} the clock syscalls did not refuse a process the way the kernel \
             refused itself\n{}",
            clock_lines(&log)
        ));
    }
    if only.len == 0 {
        return Err(format!("with {params:?} {} is on the volume and empty", only.name));
    }
    eprintln!(
        "  [clock] {params:?}: refused by name, {} carries {} bytes, boot complete",
        only.name, only.len
    );
    Ok(())
}

/// A FADT that names no century register: the machine still has a clock, and
/// the year comes from two digits and the stated assumption.
///
/// The old code could not express this state at all — it read CMOS 0x32
/// whatever the FADT said and took anything non-zero as a century — so the
/// assertion is that the *table's* answer is what decides, and that answering
/// "none" costs the machine its century rather than its clock.
pub fn no_century(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    // Both, and the second is what gives this teeth. With the register left as
    // the machine has it, honouring the FADT's "none" and ignoring it produce
    // the same year — 2000 plus two digits, and a register holding 20 — so a
    // kernel that read a hardcoded 0x32 would pass. Staging the register at the
    // *next* century separates them: honouring the table gives 2033 and
    // ignoring it gives 2133.
    const PARAMS: &[&str] = &["rtc-no-century", "rtc-century-next"];
    let (entries, log) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-no-century.img", PARAMS, &[])?;
    let logs = logs(&entries);

    if !log.contains("ACPI: the FADT names no RTC century register") {
        return Err(format!(
            "the kernel never said the FADT named no century register\n{}",
            clock_lines(&log)
        ));
    }
    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    if !only.name.starts_with(RTC_BASE_DATE) {
        return Err(format!(
            "with no century register this boot's log is {}, and two digits plus 2000 is \
             {RTC_BASE_DATE} — a name in 2133 means the register was read anyway\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    eprintln!(
        "  [clock] no century register: {}, from two digits and 2000, with the register itself \
         staged a century away",
        only.name
    );
    Ok(())
}

/// The century register's *contents* are what widen the year.
///
/// The one thing `-rtc base=` cannot stage, so the register answers 0x21 and
/// nothing else changes: same clock registers, same FADT, same decoder. A
/// kernel that ignored the register — or read a fixed 2000 — puts this boot in
/// 2033 like every other one here, and the file name is where that shows.
pub fn century_from_the_register(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    const PARAMS: &[&str] = &["rtc-century-next"];
    let (entries, log) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-century.img", PARAMS, &[])?;
    let logs = logs(&entries);

    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    // 2133 and not 2033: the same two year digits under the next century. The
    // day and time are the host's, so only the century moved.
    if !only.name.starts_with("2133-03-07-") {
        return Err(format!(
            "with the century register answering 0x21 this boot's log is {}, and the year the \
             registers describe is 2133-03-07\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    eprintln!("  [clock] century register 0x21: {}, a century past the staged clock", only.name);
    Ok(())
}
