[package]
name = "console"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
terminal = { path = "../terminal" }
toyos = { path = "../../toyos" }
toyos-abi = { path = "../../toyos-abi" }
toyos-font = { path = "../toyos-font" }
toyos-window = { path = "../toyos-window" }
