//! On-screen panic console.
//!
//! Log records rendered as an 8x16 text grid onto the UEFI GOP framebuffer,
//! armed before `serial::init`. It has no formatter of its own: a record's line
//! is `toyos_abi::log::LogRecord`'s `Display`, the same one `logd` and any
//! diagnostic tool render through, so a second formatter for a second device
//! cannot drift from the first.
//!
//! **Which records differ by caller, and that is a decision rather than an
//! accident.** A fatal path and a boot checkpoint show the *newest* records,
//! because what they are reporting is the last thing the machine did.
//! Ctrl+Alt+D shows a bracket of two instants (see [`paint_report`]), because
//! what it is reporting is one report and a tail would paginate it against a
//! whole boot's logging.
//!
//! It exists because a laptop has no serial port. On such a machine the
//! screen is the only channel a kernel panic can reach, and today a panic
//! before the compositor starts is indistinguishable from a hang.
//!
//! Two entry points on the panic path, and the split between them is the
//! load-bearing decision:
//!
//!   - [`capture`] runs at the top of the panic handler, *before* the drain in
//!     `panic_flush`. It freezes the report at the instant of the panic and
//!     consumes nothing; its own doc carries what that is worth.
//!   - [`render`] runs inside `halt_all_cpus`, *before* `panic_flush`. That
//!     ordering is only defensible because rendering consumes nothing and
//!     contains no unbounded loop, so a bug here costs the screen and never
//!     the serial report. It also means a nonce arriving on serial proves the
//!     paint already finished, which is what lets the tests skip sleeping.
//!     The early-panic branch is the one exception and inverts it: that
//!     window has no IDT, so nothing would catch a fault in here.
//!
//! A panic that *recovers* therefore captures but never paints, and
//! [`discard_capture`] drops what it captured -- otherwise the next fatal
//! path would paint a crash the machine already survived.
//!
//! The screen is smaller than the report. A 1080p panel is 67 rows and a boot
//! log is ~85 display rows before a backtrace is added, so a single paint is a
//! window over the *newest* end and everything above it would be unreachable.
//! So the text is paginated, and [`page_forever`] cycles it after the machine
//! has halted: a phone camera left running collects the whole thing. PageUp and
//! PageDown steer it, polled off the i8042 with every CPU already halted, and
//! the deadline is what a machine whose keyboard is dead, disabled or absent
//! still gets. **The first key retires the deadline for the rest of the
//! session**: a reader who has taken the wheel is reading one page, and a
//! camera that has been replaced by a person no longer needs the cycle. Paging
//! happens only when the text does not fit, and the `[page n/m]` footer is what
//! tells a photograph which slice it caught.
//!
//! That the halted machine spins rather than `hlt`s is the cost, and it is
//! paid knowingly: nothing would wake it, and re-arming the LAPIC timer would
//! aim an interrupt at the scheduler from inside a panic.
//!
//! virtio-gpu is deliberately not supported. Reaching its scanout needs
//! TRANSFER_TO_HOST_2D and RESOURCE_FLUSH through `submit_and_wait`'s
//! unbounded poll behind `GPU.lock()` -- exactly the wedge family this module
//! must not join -- and it would only buy on-screen panics in the one config
//! that already has working serial. When virtio-gpu wins device selection the
//! console detaches and draws nothing.

use core::cell::UnsafeCell;
use core::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, AtomicUsize, Ordering};

use toyos_abi::boot::{KernelArgs, MemoryMapEntry};
use toyos_ps2::{KeyDecoder, KeyOutcome};

use crate::log;
use crate::time::{Budget, Cadence, Duration};
use crate::mm::paging::CachePolicy;
use crate::mm::{self, DirectMap, align_2m};

/// 1 bpp 8x16, codepoints 0x20..=0x7E, one byte per row, bit 7 leftmost.
/// Regenerated by `cargo run -- --regen-font`; the screendump decoder in
/// `tests/common/screen.rs` reads this same file, so decoder and renderer
/// cannot drift.
static FONT: &[u8; 95 * 16] = include_bytes!("font8x16.bin");

const GLYPH_W: usize = 8;
const GLYPH_H: usize = 16;

/// Grid caps. A full exception report is ~60 lines, so 96 rows keeps the
/// whole report plus context; 320 columns covers 2560 pixels of width. Both
/// bound the stack cost of the wrap pass, which is the only array here.
const MAX_COLS: usize = 320;
const MAX_ROWS: usize = 96;

/// How much rendered log a buffer here holds, sized by the assertion below:
/// one screenful must never exceed what was captured, or the top of a page
/// would show text the snapshot never held. Paging spends the rest — at the
/// ~70 bytes per display row a kernel log actually averages, 32 KiB is around
/// five 96-row pages.
const SNAPSHOT_CAP: usize = 32 * 1024;
const _: () = assert!(SNAPSHOT_CAP >= MAX_ROWS * MAX_COLS);

/// One bit of `Rendered::alert` per byte a buffer can hold.
///
/// **A line is a newline, and a record can carry as many as it has bytes.**
/// Dividing the buffer by the shortest line the *record* formatter produces
/// assumes one record is one line, and the first message that matters breaks
/// it: `PanicInfo`'s `Display` writes `panicked at <site>:`, a newline, then
/// the panic's own text, so the panic record is two lines and every bit below
/// it would be off by one. A message of
/// nothing but newlines is one line per byte, so this is the only bound that
/// cannot be argued with. 4 KiB per buffer, 12 KiB for the three, and no
/// arithmetic anybody has to re-check.
const ALERT_WORDS: usize = SNAPSHOT_CAP.div_ceil(64);

/// How long each page stays up. Long enough to photograph, short enough that
/// a five-page report cycles inside a 15-second video.
///
/// A [`Cadence`] and not a budget: it is the rate the halted pager advances
/// at, and nothing expires.
const PAGE_HOLD: Cadence = Cadence::every(
    Duration::from_secs(3),
    "a five-page report cycles inside a 15-second video",
);

/// How long Ctrl+Alt+D's report keeps the panel. Policy, and the two ends of it
/// are a reader and a desktop: he has to notice the panel changed and raise a
/// camera, which is several of [`PAGE_HOLD`], while a machine that is still
/// scheduling has to get its own screen back without being switched off.
///
/// The two do not fight continuously. A compositor repaints on damage, and the
/// kernel drawing over the scanout behind its back is not damage in its model,
/// so each client frame costs one paint and an idle desktop produces about one
/// of those a second.
const REPORT_HOLD: Budget = Budget::of(
    Duration::from_secs(15),
    "the report stops being put back and the desktop keeps its screen",
);

/// The longest the panel may carry somebody else's paint before the report goes
/// back on it. It bounds what a photograph taken at the wrong instant loses,
/// and it is not a repaint rate: a panel nothing else draws on is *checked*
/// this often and repainted never.
const REPORT_CHECK: Cadence = Cadence::every(
    Duration::from_millis(20),
    "PROBES uncached reads per check, on the CPU that took an interrupt anyway",
);

/// The bootloader identity+high maps the first 4 GiB, and `paging::init`
/// re-maps at least that much. A framebuffer below this line is therefore
/// reachable from the first instruction of `kernel_main`; one above it is
/// only reachable after [`remap`].
const LOW_MAP_LIMIT: u64 = 4 * 1024 * 1024 * 1024;

#[derive(Clone, Copy)]
struct Fb {
    ptr: *mut u8,
    bytes: u64,
    stride_px: u32,
    width: u32,
    height: u32,
    format: u32,
}

impl Fb {
    const DETACHED: Fb = Fb {
        ptr: core::ptr::null_mut(),
        bytes: 0,
        stride_px: 0,
        width: 0,
        height: 0,
        format: 0,
    };
}

struct FbCell(UnsafeCell<Fb>);
// SAFETY: irreducible, and the reason is the same one `SEQ` below states at
// length: **the panic path may take no synchronisation primitive.** `Lock::lock`
// panics after 500M spins and `try_lock` disables preemption on entry while its
// failure path and its guard's `Drop` re-enable it, which can dispatch the
// scheduler — so no `Lock`-shaped container may hold this, and a `Cell` is not
// `Sync`. `Fb` is 40 bytes, far past any atomic. What makes the sharing sound is
// outside the type and stated where it lives: `FB` is published and read under
// the `SEQ` seqlock, and `PENDING` is written only during single-threaded boot
// and inside `set_resolution`'s window.
unsafe impl Sync for FbCell {}

/// A screenful-and-then-some of rendered log, and which of its lines an
/// `alert!` produced.
///
/// **The red row is a `Level` and never a magic value in the text.** Scanning a
/// display row for three consecutive `!` bytes makes the panel's colour depend
/// on what a message happens to contain; the record says what it is, and this
/// is where that answer survives being rendered to text.
struct Rendered {
    text: [u8; SNAPSHOT_CAP],
    /// One bit per line, **counted back from the last one**, because [`Fill`]
    /// writes the buffer from its end: a panel shows the newest records and
    /// drops the oldest, so a line's distance from the end is the only index
    /// that is fixed while the buffer is still filling.
    alert: [u64; ALERT_WORDS],
    /// Bytes of `text` in use, at its end.
    len: usize,
    lines: usize,
}

impl Rendered {
    const EMPTY: Self =
        Self { text: [0; SNAPSHOT_CAP], alert: [0; ALERT_WORDS], len: 0, lines: 0 };

    /// Render the newest records stamped in `from..=to` that fit, and return
    /// how many bytes that came to.
    ///
    /// Everything older than the buffer holds is dropped, which is the same
    /// rule the byte ring's tail had and for the same reason: a report is read
    /// from its end.
    fn render(&mut self, from: u64, to: u64) -> usize {
        self.alert = [0; ALERT_WORDS];
        self.lines = 0;
        self.len = 0;
        let mut fill = Backfill { at: SNAPSHOT_CAP, into: self };
        log::read::snapshot_committed(from, to, &mut fill);
        let at = fill.at;
        self.len = SNAPSHOT_CAP - at;
        self.len
    }

    fn view(&self) -> View<'_> {
        View {
            text: self.text.get(SNAPSHOT_CAP - self.len..).unwrap_or(&[]),
            alert: &self.alert,
            lines: self.lines,
        }
    }
}

/// A rendered log as a painter sees it.
#[derive(Clone, Copy)]
struct View<'a> {
    text: &'a [u8],
    alert: &'a [u64; ALERT_WORDS],
    lines: usize,
}

impl View<'_> {
    /// Whether line `n`, counted from the first, came from an `alert!`.
    fn is_alert(&self, n: usize) -> bool {
        let Some(from_end) = self.lines.checked_sub(n + 1) else { return false };
        self.alert.get(from_end / 64).is_some_and(|word| word & (1 << (from_end % 64)) != 0)
    }
}

/// Writes records into a [`Rendered`] back to front, so the newest are the ones
/// that survive a full buffer.
struct Backfill<'a> {
    into: &'a mut Rendered,
    /// Where the next — older — line starts.
    at: usize,
}

impl log::read::RecordSink for Backfill<'_> {
    fn put(&mut self, record: &toyos_abi::log::LogRecord) -> bool {
        let line = rendered_len(record).saturating_add(1);
        let Some(at) = self.at.checked_sub(line) else { return false };
        let Some(out) = self.into.text.get_mut(at..self.at) else { return false };
        // The same formatter measured the line, so this fills the slot exactly.
        // A disagreement would leave zeroes rather than run past the end, which
        // is the only direction a paint can afford to be wrong in.
        let mut into = Into { out, at: 0 };
        let _ = core::fmt::write(&mut into, format_args!("{record}\n"));

        // **Counted in newlines and not in records**, because `paint` counts in
        // newlines: a record whose message carries one — every panic, whose
        // `PanicInfo` writes `panicked at <site>:` and then the message — is two
        // rows on the panel and needs two bits, or the second renders white and
        // every bit below it is off by one.
        let lines = out.iter().filter(|&&byte| byte == b'\n').count();
        if record.level() == Some(log::Level::Alert) {
            for line in self.into.lines..self.into.lines + lines {
                if let Some(word) = self.into.alert.get_mut(line / 64) {
                    *word |= 1 << (line % 64);
                }
            }
        }
        self.into.lines += lines;
        self.at = at;
        true
    }
}

/// What one record's line costs, without rendering it anywhere.
fn rendered_len(record: &toyos_abi::log::LogRecord) -> usize {
    struct Count(usize);
    impl core::fmt::Write for Count {
        fn write_str(&mut self, s: &str) -> core::fmt::Result {
            self.0 = self.0.saturating_add(s.len());
            Ok(())
        }
    }
    let mut count = Count(0);
    let _ = core::fmt::write(&mut count, format_args!("{record}"));
    count.0
}

/// A `fmt::Write` over a fixed slot that drops what does not fit instead of
/// panicking, because the one caller is a crash report.
struct Into<'a> {
    out: &'a mut [u8],
    at: usize,
}

impl core::fmt::Write for Into<'_> {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        let end = self.at.saturating_add(s.len());
        if let Some(slot) = self.out.get_mut(self.at..end) {
            slot.copy_from_slice(s.as_bytes());
            self.at = end;
        }
        Ok(())
    }
}

struct RenderedCell(UnsafeCell<Rendered>);
// SAFETY: irreducible for the same reason as `FbCell` — a `Lock` may not be
// reached from the panic path — and more so: `Rendered` is `SNAPSHOT_CAP` bytes
// of text plus its alert bitmap, so it is a `static` by construction and can be
// neither copied out nor atomically swapped. What serialises the three cells is
// `PAINTING`, taken by every painter without exception, plus the fact that
// `SNAPSHOT` is written once by `capture` and never again.
unsafe impl Sync for RenderedCell {}

/// Seqlock over `FB`. Even means stable, odd means a publisher is inside.
/// Not a `Lock` and not even a `try_lock`: `Lock::lock` panics after 500M
/// spins, and `try_lock` disables preemption on entry while its failure path
/// and its guard's `Drop` re-enable it -- which dispatches `do_preempt` when
/// the count hits zero with `need_resched` set. The panic path must not be
/// able to reach the scheduler. A publisher that dies mid-update leaves `SEQ`
/// odd forever, which costs the screen and nothing else.
static SEQ: AtomicU32 = AtomicU32::new(0);
static FB: FbCell = FbCell(UnsafeCell::new(Fb::DETACHED));

/// Exactly one painter at a time, taken by every painter without exception.
/// Closes three modes with one instruction: two CPUs panicking at once, a
/// fault *inside* the renderer (#PF -> fatal_exception -> halt_all_cpus ->
/// re-entry -> latch -> return, so the recursion terminates at depth one),
/// and double-panic re-entry through `halt_all_cpus`.
///
/// [`render`] never releases it, which is what stops a later boot checkpoint
/// from painting over a fatal report; every fatal caller ends in `hlt`.
/// [`boot_checkpoint`] does release it, because the machine keeps running.
static PAINTING: AtomicBool = AtomicBool::new(false);

static SNAPSHOT: RenderedCell = RenderedCell(UnsafeCell::new(Rendered::EMPTY));

/// True means, and only means, "a panic that has *not* been recovered captured
/// this report". [`capture`] establishes the first half and
/// [`discard_capture`] the second: without it a survived panic's report stays
/// here and a later, unrelated fatal path paints it as the cause of death.
static CAPTURED: AtomicBool = AtomicBool::new(false);

/// Scratch for the readers that render the *live* shards: a boot checkpoint,
/// and a fatal path that never ran the panic handler. Separate from `SNAPSHOT`
/// because a checkpoint sharing it would erase a report another CPU had
/// already captured and not yet painted.
static LIVE: RenderedCell = RenderedCell(UnsafeCell::new(Rendered::EMPTY));

/// Ctrl+Alt+D's report, rendered the moment it is complete.
///
/// A third buffer and not a third reader of the shards, because the report has
/// to survive being repainted: [`hold_report`] puts it back on the panel for
/// [`REPORT_HOLD`], and by then the ring holds whatever the machine has said
/// since. A screenful is all a repaint can show and `SNAPSHOT_CAP` is five of
/// those, so nothing here is sized for the paging the report does not do.
static REPORT: RenderedCell = RenderedCell(UnsafeCell::new(Rendered::EMPTY));

/// When the report gives the panel back. 0 means it does not hold it.
static HOLD_UNTIL: AtomicU64 = AtomicU64::new(0);
/// The next `nanos_since_boot` at which a CPU may look at the panel. A CAS, so
/// one CPU of the eight in `drain_irqs` does the looking.
static HOLD_CHECK_AT: AtomicU64 = AtomicU64::new(0);

/// Set the first time a process claims `DeviceType::Framebuffer`. Boot checkpoints
/// stop repainting once something owns the screen; a *fatal* panic ignores
/// this entirely and takes the screen back unconditionally.
static SCREEN_OWNED_BY_USERLAND: AtomicBool = AtomicBool::new(false);

/// When userland took the screen, so [`probe_due`] can wait a few seconds past
/// it. 0 means it has not.
#[cfg(feature = "boot-actuators")]
static CLAIMED_AT: core::sync::atomic::AtomicU64 = core::sync::atomic::AtomicU64::new(0);

/// How long after the claim the probe fires. Long enough for a desktop to
/// finish coming up and for whoever is watching the panel to be watching it.
#[cfg(feature = "boot-actuators")]
const PROBE_DELAY_NS: u64 = 5_000_000_000;

/// Whether the `metal-panic-probe` boot should panic now. The idle loop asks,
/// because a CPU there has no thread current and therefore takes the panic
/// handler's fall-through to `halt_all_cpus` rather than its recovery branch —
/// which is the whole point of the probe: the recovery branch never paints.
#[cfg(feature = "boot-actuators")]
pub fn probe_due() -> bool {
    if !crate::actuator::metal_panic_probe() {
        return false;
    }
    let at = CLAIMED_AT.load(Ordering::Relaxed);
    if at == 0 || crate::clock::nanos_since_boot().saturating_sub(at) < PROBE_DELAY_NS {
        return false;
    }
    // Exactly one CPU, and that is not tidiness. Every idle CPU reaches this
    // inside the same microsecond, so without the latch the machine takes as
    // many simultaneous panics as it has idle cores and there is no CPU left in
    // an idle loop to put the report on `/log`.
    static FIRED: AtomicBool = AtomicBool::new(false);
    FIRED.compare_exchange(false, true, Ordering::AcqRel, Ordering::Relaxed).is_ok()
}

/// Hand the screen over, and do not return while a checkpoint is still
/// drawing on it.
///
/// Setting the flag stops the *next* checkpoint. It does nothing about the one
/// already inside `paint`, which took `PAINTING` before the flag was set and
/// goes on writing glyphs for as long as a full-panel paint takes — and that
/// is not a short time on the machine this matters on. `paint` writes one
/// `write_volatile` per pixel into a mapping firmware left uncached, measured
/// at ~460 ms for 1920x1080 on real hardware, against microseconds under QEMU where
/// the framebuffer is host RAM. So the window is invisible to every test in
/// the suite and half a second wide on the laptop.
///
/// A claimer that returns inside that window maps the scanout and starts
/// composing against a screen the kernel is still painting, and whatever the
/// checkpoint writes afterwards stays: a damage-tracked client repaints what
/// its model says changed, and the model has no idea any of this happened.
/// That leaves kernel log glyphs sitting in cells the client believes are
/// blank, for the life of the session.
///
/// Waiting is bounded by one paint and happens once per boot. Abandoning the
/// paint instead would be cheaper and wrong: it leaves the half of the screen
/// already painted on the glass, which is the same corruption.
pub fn screen_claimed_by_userland() {
    SCREEN_OWNED_BY_USERLAND.store(true, Ordering::SeqCst);
    #[cfg(feature = "boot-actuators")]
    CLAIMED_AT.store(crate::clock::nanos_since_boot().max(1), Ordering::Relaxed);
    // Bounded because a CPU that died holding the latch must not take the
    // display down with it; one paint is the honest ceiling and this is twice
    // the slowest one measured.
    const CHECKPOINT: Budget = Budget::of(
        Duration::from_secs(2),
        "the claimer proceeds and says so, rather than the display going down with a dead CPU",
    );
    let deadline = crate::clock::nanos_since_boot() + CHECKPOINT.nanos();
    while PAINTING.load(Ordering::SeqCst) {
        if crate::clock::nanos_since_boot() > deadline {
            log!("panic console: claim waited 2s for a checkpoint that never finished");
            return;
        }
        core::hint::spin_loop();
    }
}

/// The descriptor [`arm`] validated, held so [`remap`] and [`rearm`] can
/// re-publish it without re-deriving anything. A null pointer here means
/// there is no usable GOP framebuffer at all, and no later call can invent
/// one. Written only during single-threaded boot.
static PENDING: FbCell = FbCell(UnsafeCell::new(Fb::DETACHED));
static RAW_PHYS: AtomicU64 = AtomicU64::new(0);
static RAW_SIZE: AtomicU64 = AtomicU64::new(0);

/// Boot-time and `set_resolution`-window only, so the load-then-store of `SEQ`
/// needs no CAS: publishers never race each other, only readers.
fn publish(fb: Fb) {
    let seq = SEQ.load(Ordering::Relaxed);
    SEQ.store(seq.wrapping_add(1), Ordering::Relaxed);
    // Both fences are the seqlock, and neither is decoration. A release *RMW*
    // on the odd transition would order what precedes it, not what follows,
    // leaving the compiler free to hoist the descriptor store above the odd
    // marker -- at which point a reader that saw an even sequence on both
    // sides could still have read a half-written descriptor.
    core::sync::atomic::fence(Ordering::Release);
    // SAFETY: irreducible — this is the seqlock's payload store, and the seqlock
    // exists because the panic path may take no lock (see `SEQ`). Sound on the
    // protocol around it: `SEQ` is odd across this write, so a concurrent
    // `snapshot` discards whatever it read, and the two fences are what keep the
    // store between the odd and even markers. Publishers never race each other —
    // this is boot-time and `set_resolution`-window only, which is why the
    // load-then-store of `SEQ` above needs no CAS.
    unsafe { *FB.0.get() = fb };
    SEQ.store(seq.wrapping_add(2), Ordering::Release);
}

/// Stop painting until the next [`rearm`]. For a window in which the
/// framebuffer may be freed and reallocated under us: the worst case becomes
/// "no console", never a write into whatever took its place.
pub fn detach() {
    publish(Fb::DETACHED);
}

/// Re-publish the armed descriptor after such a window.
pub fn rearm() {
    // SAFETY: irreducible — `PENDING` is an `UnsafeCell` for the reason
    // `FbCell` states. Sound because `PENDING` is written only during
    // single-threaded boot (`arm`) and by `disable`, and `rearm` is called from
    // the same single-threaded sequence and from `set_resolution`'s window,
    // which is the one place two of these can be in flight — and that window is
    // itself entered by one CPU. `Fb` is `Copy`, so this takes a copy and holds
    // no reference into the cell.
    let fb = unsafe { *PENDING.0.get() };
    if validate(&fb) {
        publish(fb);
    }
}

/// Give up the display permanently. Called when virtio-gpu wins device
/// selection: its scanout is unreachable from the panic path, and clearing
/// PENDING is what stops a later `rearm` from resurrecting the firmware
/// framebuffer nobody is scanning out any more.
pub fn disable() {
    // SAFETY: irreducible and sound for the same reasons as `rearm`'s read:
    // `PENDING` has one writer at a time and this is called from the boot
    // sequence, when virtio-gpu wins device selection.
    unsafe { *PENDING.0.get() = Fb::DETACHED };
    RAW_PHYS.store(0, Ordering::Relaxed);
    detach();
}

/// Torn means unavailable, never a wild pointer -- and that has to hold on
/// the ordering, not on the values. Today only two descriptors are ever
/// published, one `validate`d and one all-zero, so every torn mixture is
/// caught downstream by the null check below, by `bytes == 0` collapsing
/// `row_base`/`put_pixel` to no-ops, or by `width == 0` giving `cols == 0`.
/// The moment a *second valid* descriptor exists -- which `detach`/`rearm`
/// anticipate -- that argument is gone and only the fences are left.
fn snapshot() -> Option<Fb> {
    for _ in 0..4 {
        let before = SEQ.load(Ordering::Acquire);
        if before & 1 != 0 {
            continue;
        }
        // SAFETY: irreducible — the seqlock's payload read, and the seqlock is
        // here because the panic path may take no lock. This is the one place
        // in the module that reads `FB` while a publisher may be inside it, and
        // it is sound on the protocol rather than on exclusion: the `SEQ`
        // comparison below discards a value read across a publication, and the
        // paragraph above this function states what a torn value can and cannot
        // be — every torn mixture of the two descriptors that are ever
        // published is caught downstream by the null check, by `bytes == 0`
        // collapsing `row_base`/`put_pixel` to no-ops, or by `width == 0`
        // giving `cols == 0`.
        let fb = unsafe { *FB.0.get() };
        core::sync::atomic::fence(Ordering::Acquire);
        if SEQ.load(Ordering::Relaxed) == before {
            return (!fb.ptr.is_null()).then_some(fb);
        }
    }
    None
}

/// Reject a descriptor that could turn a panic into a wild write. Geometry
/// bounds keep every later product inside `u64`, and the kernel-address check
/// keeps the base inside the direct map.
fn validate(fb: &Fb) -> bool {
    if fb.ptr.is_null() || !mm::is_kernel_addr(fb.ptr as u64) {
        return false;
    }
    if !(1..=16384).contains(&fb.width) || !(1..=16384).contains(&fb.height) {
        return false;
    }
    if fb.stride_px < fb.width || fb.stride_px > 65536 {
        return false;
    }
    let needed = (fb.stride_px as u64)
        .checked_mul(fb.height as u64)
        .and_then(|v| v.checked_mul(4));
    matches!(needed, Some(n) if fb.bytes >= n)
}

/// Whether the UEFI memory map hands `phys` to the PMM as free RAM.
///
/// A firmware GOP that is a shim over memory the kernel later re-owns would
/// make the panic path a write into the heap. `pmm::is_usable` counts
/// `BootServicesData` and `LoaderData` as free, so this is not hypothetical
/// on firmware that allocates its scanout from boot services.
fn framebuffer_is_reclaimed_ram(maps: &[MemoryMapEntry], phys: u64) -> Option<u32> {
    let entry = maps.iter().find(|e| phys >= e.start && phys < e.end)?;
    mm::pmm::is_usable_type(entry.uefi_type).then_some(entry.uefi_type)
}

/// Arm the console from `KernelArgs`, before `serial::init`.
///
/// Everything from here to `mm::init` -- including `serial::init`'s own UART
/// probe -- is covered, because the bootloader's identity+high map already
/// reaches a sub-4 GiB framebuffer and no kernel mapping exists yet.
pub fn arm(args: &KernelArgs, maps: &[MemoryMapEntry]) {
    if args.gop_framebuffer == 0 {
        return;
    }

    if let Some(uefi_type) = framebuffer_is_reclaimed_ram(maps, args.gop_framebuffer) {
        log!(
            "panic console: disarmed, framebuffer at {:#x} is UEFI type {} (PMM-owned RAM)",
            args.gop_framebuffer,
            uefi_type
        );
        return;
    }

    let fb = Fb {
        ptr: DirectMap::from_phys(args.gop_framebuffer).as_mut_ptr::<u8>(),
        bytes: args.gop_framebuffer_size,
        stride_px: args.gop_stride,
        width: args.gop_width,
        height: args.gop_height,
        format: args.gop_pixel_format,
    };
    if !validate(&fb) {
        log!(
            "panic console: disarmed, bad descriptor {}x{} stride={} size={:#x}",
            args.gop_width, args.gop_height, args.gop_stride, args.gop_framebuffer_size
        );
        return;
    }

    // SAFETY: irreducible and sound for the same reasons as `disable`'s write.
    // `arm` runs once, during single-threaded boot, before any AP is started.
    unsafe { *PENDING.0.get() = fb };
    RAW_PHYS.store(args.gop_framebuffer, Ordering::Relaxed);
    RAW_SIZE.store(args.gop_framebuffer_size, Ordering::Relaxed);

    match args.gop_framebuffer.checked_add(args.gop_framebuffer_size) {
        Some(end) if end <= LOW_MAP_LIMIT => {
            publish(fb);
            log!(
                "panic console: armed {}x{} stride={} format={} at {:#x}",
                fb.width, fb.height, fb.stride_px, fb.format, args.gop_framebuffer
            );
        }
        _ => log!(
            "panic console: framebuffer at {:#x} is above the boot map, armed after mm::init",
            args.gop_framebuffer
        ),
    }
}

/// Re-establish the mapping after `mm::init` replaces the bootloader's page
/// tables, and arm a framebuffer that sits above the boot map's 4 GiB reach.
pub fn remap() {
    let phys = RAW_PHYS.load(Ordering::Relaxed);
    if phys == 0 {
        return;
    }
    let size = RAW_SIZE.load(Ordering::Relaxed);
    mm::paging::map_mmio(phys, align_2m(size as usize) as u64, CachePolicy::WriteCombining);
    rearm();
}

/// Render the newest records into the console's static scratch.
///
/// Called at the top of the panic handler, before `panic_flush` drains the
/// records to the console. No pixels, no lock, no mutation of the shards -- one bounded
/// newest-first walk on a path that is about to halt. Skipped entirely when no
/// framebuffer is armed, which is every headless boot, so a panic storm on a
/// server pays nothing.
///
/// **Nothing in the tree distinguishes capture-present from capture-absent.** A
/// record drain moves a cursor and leaves every shard where it was, so
/// [`live_tail`] after the flush returns the same text — and with the body of
/// this function replaced by `return`, `screen_late_panic` still passes.
///
/// What keeps it here is narrower: this freezes the report at the instant of
/// the panic, while `live_tail` re-reads a ring that siblings are still writing
/// to. The halt IPI is maskable, so a CPU with IF=0 keeps running until it
/// re-enables, and one spinning in a `log!` loop can push 32 KiB through the
/// ring between the panic and the paint -- which would push the report off the
/// tail. That is unlikely and unstaged.
///
/// So: delete it if you can stage that race and show it does not matter, or if
/// you decide a diluted tail is an acceptable worst case. Do not delete it on
/// the grounds that the tests still pass, because they will.
pub fn capture() {
    if snapshot().is_none() {
        return;
    }
    // SAFETY: irreducible — `Rendered` is too large to be anything but a
    // `static`, and the panic path may take no lock to guard it. Sound because
    // `SNAPSHOT` is written here and nowhere else, and `capture` is called once
    // per panic from the panic handler, which `panic::PANICKING` already
    // serialises to one CPU; the readers (`fatal_text`) run after it on the same
    // CPU, or on another that reaches them only through `PAINTING`.
    let into = unsafe { &mut *SNAPSHOT.0.get() };
    CAPTURED.store(into.render(0, u64::MAX) > 0, Ordering::Relaxed);
}

/// Drop the captured report: this panic was survived, so it is no longer
/// anyone's cause of death. Called on the recovery branch, which is the only
/// exit from the panic handler that does not paint.
pub fn discard_capture() {
    CAPTURED.store(false, Ordering::Relaxed);
}

/// Re-freeze the captured report, so a line the kernel writes *after*
/// [`capture`] is part of what the panel paints.
///
/// **One caller and it is why this exists**: `apic::wait_for_log_file` says on
/// the record ring that its budget is spent and the panel is the only copy —
/// and it says it after [`capture`] has already run, so without this the
/// sentence reaches no channel at all on the one machine that wait exists for,
/// which has no serial port and whose `/log` is the thing that did not answer.
///
/// **Only refreshes a capture that is already there.** A fatal path that never
/// ran the panic handler paints [`live_tail`], which re-peeks the shards and
/// therefore carries the line already; taking the snapshot for it would freeze
/// a report it deliberately reads live.
///
/// Same CPU, same panic, and before this CPU has taken [`PAINTING`] — so it
/// adds no reader/writer pair that [`capture`]'s own argument did not already
/// have.
pub fn refresh_capture() {
    if !CAPTURED.load(Ordering::Relaxed) {
        return;
    }
    capture();
}

/// The tail of the live shards, for callers with nothing captured. Consumes
/// nothing — a record drain moves a cursor and leaves every shard where it was
/// — so a later `panic_flush` reports the same records identically.
fn live_tail() -> View<'static> {
    // SAFETY: irreducible for the same reason as `capture`'s `SNAPSHOT` write.
    // Sound because `LIVE` is reached only from here and every caller holds
    // `PAINTING`, which is taken by every painter without exception. One block
    // and not the two this used to be: the `&'static mut` is reborrowed as the
    // `&'static` the `View` needs rather than dereferencing the cell a second
    // time, which also makes it impossible for the render and the view to be of
    // different things.
    let into: &'static mut Rendered = unsafe { &mut *LIVE.0.get() };
    into.render(0, u64::MAX);
    let rendered: &'static Rendered = into;
    rendered.view()
}

// DESIGN RULE: render and everything it calls acquires NO synchronization
// primitive -- not `Lock::lock`, not `Lock::try_lock`, not `BackendGuard`.
// try_lock is banned too: it disables preemption on entry and
// its failure path re-enables it, which can dispatch the scheduler. No
// allocation, no `use alloc::`, no `&dyn`, no unwrap/expect/[]. Checked or
// saturating arithmetic only -- overflow-checks are on, so an overflow here is
// a panic inside a panic. Every framebuffer write is clamped to the published
// byte count. Stack budget is 256 bytes plus the one wrap array; the double
// fault path runs on IST1, which is 16384 bytes and already partly consumed by
// kernel_backtrace_safe -- `percpu.rs` carries the 6,688 bytes the whole report
// was measured using, `ist1_report` off a real #DF with the record merge and
// the paint included.

/// What a fatal path paints: the captured report, or -- for a path that
/// reached `halt_all_cpus` without the panic handler, a fatal exception or the
/// scheduler abort -- the live ring, which still holds it.
///
/// Idempotent for the captured case, which is the one [`page_forever`] walks
/// repeatedly: `SNAPSHOT` is written once and never again. The live branch
/// re-peeks, and tolerates a sibling still logging for the same reason
/// [`live_tail`] always did.
fn fatal_text() -> View<'static> {
    if CAPTURED.load(Ordering::Relaxed) {
        // SAFETY: irreducible for the same reason as `capture`'s write. Sound
        // because `CAPTURED` is true, which means `capture` finished writing
        // `SNAPSHOT` and it is never written again — this branch is idempotent,
        // which is what lets `page_forever` walk it repeatedly.
        unsafe { &*SNAPSHOT.0.get() }.view()
    } else {
        live_tail()
    }
}

/// Paint the newest page of the captured report. Fatal paths only. Returns
/// whether this call is the one that took the screen, which is what entitles
/// its caller -- and only its caller -- to go on to [`page_forever`].
pub fn render() -> bool {
    if PAINTING.swap(true, Ordering::SeqCst) {
        return false;
    }
    paint(Fill::Fatal, fatal_text(), Page::Last, Watch::No);
    true
}

/// Cycle the report across the screen until the machine is switched off.
///
/// Reached only from `halt_all_cpus`, only after `panic_flush`, and only on
/// the CPU whose [`render`] took `PAINTING` -- so the serial report is already
/// out and nothing here can cost it, and no second CPU can be painting
/// alongside. Returns without looping when there is nothing to page: a single
/// page, no framebuffer, or a panic early enough that the TSC is uncalibrated
/// and there is no deadline to wait on.
///
/// The panic handler's other two exits call [`render`] and not this, and the
/// reasons are different. The early-boot branch is before `clock::init`, so
/// the deadline does not exist yet -- and its report is four rows. The reentry
/// branch is a panic inside the panic path: it has to stop, not settle into a
/// loop that would keep a CPU in the code that just faulted.
pub fn page_forever() {
    if !crate::clock::calibrated() {
        return;
    }
    let text = fatal_text();
    let Some(fb) = snapshot() else { return };
    let Some((cols, grid_rows)) = geometry(&fb) else { return };
    let (_, pages, _) = pagination(text.text, cols, grid_rows);
    if pages < 2 {
        return;
    }
    // `None` is the screenful [`render`] left up, which is `Page::Last` and so
    // not one of the numbered pages: the deadline's first turn starts the cycle
    // at the top, and a key from there reaches either end of it.
    let mut shown: Option<usize> = None;
    let mut keys = KeyDecoder::new();
    // Once the reader has steered, the cycle is his and the deadline never runs
    // again. There is no way back to automatic paging, and none is wanted: the
    // page he stopped on is the one he is photographing.
    let mut steered = false;
    loop {
        let step = hold((!steered).then_some(PAGE_HOLD.nanos()), &mut keys);
        steered |= step.is_some();
        let next = match (shown, step.unwrap_or(PageKey::Down)) {
            (None, PageKey::Down) => 0,
            (None, PageKey::Up) => pages - 1,
            (Some(page), PageKey::Down) => (page + 1) % pages,
            (Some(page), PageKey::Up) => (page + pages - 1) % pages,
        };
        paint(Fill::Fatal, text, Page::Nth(next), Watch::No);
        shown = Some(next);
    }
}

/// Which way the next paint moves.
#[derive(Clone, Copy)]
enum PageKey {
    Up,
    Down,
}

/// HID usages, because that is what the wire decoder emits and this module has
/// no business knowing a scancode.
const HID_PAGE_UP: u8 = 0x4B;
const HID_PAGE_DOWN: u8 = 0x4E;

/// Wait for a page key, giving up after `nanos` if there is a deadline at all.
/// `None` back is the deadline expiring, and is unreachable without one.
///
/// `nanos_since_boot` is an `rdtsc` and two relaxed loads and [`i8042::poll_byte`]
/// is an `inb` of the status port -- no lock, no MMIO, nothing the panic path is
/// forbidden to touch, and no wait a controller could extend. The deadline is
/// what a machine with no keyboard gets, and it only ever goes forward.
///
/// [`i8042::poll_byte`]: crate::drivers::i8042::poll_byte
fn hold(nanos: Option<u64>, keys: &mut KeyDecoder) -> Option<PageKey> {
    let target = nanos.map(|n| crate::clock::nanos_since_boot().saturating_add(n));
    while target.is_none_or(|t| crate::clock::nanos_since_boot() < t) {
        // The pointer shares the port, and its packet bytes are scancodes to
        // anything that does not skip them.
        if let Some((byte, false)) = crate::drivers::i8042::poll_byte() {
            match keys.feed(byte) {
                KeyOutcome::Key { usage: HID_PAGE_UP, pressed: true } => return Some(PageKey::Up),
                KeyOutcome::Key { usage: HID_PAGE_DOWN, pressed: true } => {
                    return Some(PageKey::Down);
                }
                _ => {}
            }
        }
        core::hint::spin_loop();
    }
    None
}

/// Repaint at a boot phase boundary, so a machine that wedges later still
/// shows how far it got. Converts "black screen" into "NVMe came up, xHCI
/// did not" for free, which is the only coverage there is for a hang that
/// never panics.
pub fn boot_checkpoint() {
    if SCREEN_OWNED_BY_USERLAND.load(Ordering::Relaxed) {
        return;
    }
    // The same latch, taken the same way: an AP that misses `boot_aps`' 100 ms
    // deadline can panic while the BSP is inside a checkpoint, and a plain
    // load here would let the checkpoint paint over its report. Losing the race
    // costs a checkpoint or one fatal repaint; serial reports either way.
    if PAINTING.swap(true, Ordering::SeqCst) {
        return;
    }
    paint(Fill::Boot, live_tail(), Page::Last, Watch::No);
    PAINTING.store(false, Ordering::SeqCst);
}

/// Put the log between two marks on the panel, and keep it there.
///
/// [`boot_checkpoint`] without the userland check, and that is the first of two
/// differences. The caller is Ctrl+Alt+D, pressed on a machine its owner
/// believes has stopped, and the machine this exists for has no serial port —
/// so declining because a compositor holds the screen would answer the
/// question into a log file nothing is left running to flush. The keystroke is
/// the consent.
///
/// The second difference is the bracket. A tail of the ring is whatever the
/// machine last said, and a boot log is mostly not an answer to the question
/// the key asked — worse, the tail paginates over the *whole* ring, so the
/// panel shows one slice of a log and the verdict is on it by luck. A bracket
/// is one report: it fits a screen, there is no page for the answer to be on
/// the wrong side of, and its last line is the verdict whatever else the
/// machine logs while the CPUs are answering.
///
/// **A single paint is not a report.** Whoever owns the screen goes on
/// composing and has no idea the kernel drew, so what a photograph catches is
/// whatever survived the next client frame. The paint therefore arms a hold,
/// and [`hold_report`] is the other half.
/// **The bracket is two timestamps and not two byte positions**, and that is
/// better rather than a concession. A byte position has no meaning across
/// shards — there is no single stream for it to be a position in — and the
/// dump's own records are stamped by the same clock the bracket is taken from,
/// so the report is exactly the records the dump produced. A byte range could
/// be widened by any concurrent writer.
pub fn paint_report(from: u64, to: u64) {
    // SAFETY: irreducible for the same reason as `capture`'s `SNAPSHOT` write.
    // Sound because `REPORT` is reached only from here and `report_text`, and
    // `paint_report` is called from the Ctrl+Alt+D dump on one CPU — the
    // request reschedules every CPU and the dump itself is what produces the
    // bracket, so there is one in flight at a time.
    let into = unsafe { &mut *REPORT.0.get() };
    into.render(from, to);
    HOLD_UNTIL.store(
        crate::clock::nanos_since_boot().saturating_add(REPORT_HOLD.nanos()),
        Ordering::Relaxed,
    );
    paint_held_report();
}

/// The report as it was when the dump finished, for however long the hold
/// lasts. Empty until one has been asked for.
fn report_text() -> View<'static> {
    // SAFETY: irreducible for the same reason as `paint_report`'s write. Sound
    // because both callers reach this after `paint_report` returned — the
    // render is complete — and `paint_held_report` holds `PAINTING`.
    unsafe { &*REPORT.0.get() }.view()
}

fn paint_held_report() {
    if PAINTING.swap(true, Ordering::SeqCst) {
        return;
    }
    paint(Fill::Boot, report_text(), Page::Last, Watch::Yes);
    PAINTING.store(false, Ordering::SeqCst);
}

/// Put the report back if the panel has stopped carrying it. Called from
/// `drain_irqs` on every CPU, every pass.
///
/// It repaints on evidence rather than on a timer, and the difference is the
/// photograph. A machine that has genuinely stopped has nobody to draw over the
/// report, so this costs it [`PROBES`] uncached reads every [`REPORT_CHECK`]
/// and never a paint — where a timer would blank and redraw the panel every
/// tick, and a camera that caught the fill would come away with a black frame.
/// A machine whose compositor is still running pays a paint per overwrite until
/// the hold expires, which is the cost of answering at all on that machine.
pub fn hold_report() {
    let until = HOLD_UNTIL.load(Ordering::Relaxed);
    if until == 0 {
        return;
    }
    let now = crate::clock::nanos_since_boot();
    if now >= until {
        HOLD_UNTIL.store(0, Ordering::Relaxed);
        return;
    }
    let due = HOLD_CHECK_AT.load(Ordering::Relaxed);
    if now < due
        || HOLD_CHECK_AT
            .compare_exchange(
                due,
                now.saturating_add(REPORT_CHECK.nanos()),
                Ordering::AcqRel,
                Ordering::Relaxed,
            )
            .is_err()
    {
        return;
    }
    let Some(fb) = snapshot() else { return };
    if !mapped(&fb) || panel_carries_report(&fb) {
        return;
    }
    log!("panic console: the panel was drawn over, putting the report back");
    paint_held_report();
}

/// Which slice of the text a paint shows.
#[derive(Clone, Copy)]
enum Page {
    /// The newest screenful, whatever the page grid says. A report must fill
    /// the screen it is painted on; a page-aligned last page would leave the
    /// bottom two thirds blank whenever the row count divides badly.
    Last,
    Nth(usize),
}

/// The fill colour carries "halted" versus "still booting" at zero cost, and
/// the fill itself is the proof the console ran *this* boot rather than a
/// stale frame surviving.
#[derive(Clone, Copy)]
enum Fill {
    Fatal,
    Boot,
}

/// The text grid a framebuffer offers, or `None` when it offers none.
fn geometry(fb: &Fb) -> Option<(usize, usize)> {
    let cols = (fb.width as usize / GLYPH_W).min(MAX_COLS);
    let rows = (fb.height as usize / GLYPH_H).min(MAX_ROWS);
    (cols != 0 && rows != 0).then_some((cols, rows))
}

/// Display rows `text` occupies, wrapping at `cols`.
///
/// Wrap, do not clip: a backtrace line carrying a demangled Rust symbol
/// routinely exceeds 160 columns and the symbol is the single most valuable
/// token on the screen.
fn count_rows(text: &[u8], cols: usize) -> usize {
    let mut rows = 1;
    let mut col = 0usize;
    let mut i = 0usize;
    while i < text.len() {
        let newline = text[i] == b'\n';
        i += 1;
        col += 1;
        if newline || col == cols {
            rows += 1;
            col = 0;
        }
    }
    rows
}

/// Total display rows, pages, and rows per page.
///
/// A text that fits gets the whole grid and one page, so a screen that never
/// needs paging is byte-identical to one a console without paging would draw.
/// One that does not fit gives the bottom row to the `[page n/m]` footer,
/// because
/// a paging console whose page nobody can identify is a slideshow.
fn pagination(text: &[u8], cols: usize, grid_rows: usize) -> (usize, usize, usize) {
    let total = count_rows(text, cols);
    if total <= grid_rows || grid_rows < 2 {
        return (total, 1, grid_rows);
    }
    let per = grid_rows - 1;
    (total, total.div_ceil(per), per)
}

/// Where a display row starts, and which log line it is part of.
///
/// The second half is what carries [`Level`] through the wrap: a line wider
/// than the grid occupies several display rows, and the colour is a property of
/// the record rather than of any one row of it.
#[derive(Clone, Copy)]
struct Row {
    at: u32,
    line: u32,
}

/// Display rows `first ..`, one per slot in `out`. Rows past the end get
/// `text.len()`, which draws nothing.
fn row_offsets(text: &[u8], cols: usize, first: usize, out: &mut [Row]) {
    let len = text.len();
    for slot in out.iter_mut() {
        *slot = Row { at: len as u32, line: 0 };
    }
    if first == 0 {
        if let Some(slot) = out.first_mut() {
            *slot = Row { at: 0, line: 0 };
        }
    }
    let mut row = 0usize;
    let mut col = 0usize;
    let mut i = 0usize;
    let mut line = 0u32;
    while i < len {
        let newline = text[i] == b'\n';
        i += 1;
        col += 1;
        if newline {
            line += 1;
        }
        if newline || col == cols {
            row += 1;
            col = 0;
            if row >= first {
                let slot = row - first;
                if slot >= out.len() {
                    return;
                }
                out[slot] = Row { at: i as u32, line };
            }
        }
    }
}

/// Whether a later pass has to be able to tell this paint apart from the panel
/// having been drawn over.
///
/// Only the report does, and it is the only paint anything is expected to put
/// back: a checkpoint's screen is superseded by the next phase and a fatal
/// one's by nothing, because that machine is halted. Saying so at the call site
/// is what stops a checkpoint that ran during a hold from becoming the image
/// [`hold_report`] preserves.
#[derive(Clone, Copy, PartialEq)]
enum Watch {
    No,
    Yes,
}

/// Pixels of the watched paint remembered, so a later pass can tell "the report
/// is still up" from "something drew over it" without keeping a copy of the
/// panel.
const PROBES: usize = 128;

/// How many of those are a grid over the whole panel rather than ink of the
/// text. Both halves are load-bearing and neither replaces the other: the grid
/// notices a repaint where the report has no glyphs — a taskbar below a short
/// report, the strip under the last cell row — and the ink notices one that
/// writes its own background over the text, which a grid probe sitting on the
/// report's own black background cannot tell from the report still being up.
const GRID_PROBES: usize = 32;
const GRID_COLS: usize = 8;
const GRID_ROWS: usize = GRID_PROBES / GRID_COLS;
const _: () = assert!(GRID_COLS > 1 && GRID_ROWS > 1);

/// One ink probe every this many inked glyphs, so the set spans the page rather
/// than clustering in its first line — and so a client that repaints one band
/// of the panel is seen by the probes inside that band.
const PROBE_STRIDE: usize = 29;

static PROBE_AT: [AtomicU32; PROBES] = [const { AtomicU32::new(0) }; PROBES];
static PROBE_PX: [AtomicU32; PROBES] = [const { AtomicU32::new(0) }; PROBES];
static PROBE_N: AtomicUsize = AtomicUsize::new(0);

fn paint(fill: Fill, view: View, page: Page, watch: Watch) {
    let Some(fb) = snapshot() else { return };
    if !mapped(&fb) {
        return;
    }
    let Some((cols, grid_rows)) = geometry(&fb) else { return };
    let text = view.text;
    let len = text.len();
    let (total, pages, per) = pagination(text, cols, grid_rows);
    // `Last` is the newest `per` rows rather than page `pages - 1`, so the two
    // agree on a text that divides evenly and `Last` still fills the screen
    // when it does not. The overlap that buys is a few repeated rows at the
    // end of a cycle, which is the cheap direction to be wrong in -- but it
    // does mean the footer's number cannot be derived from `first`.
    let newest = total.saturating_sub(per);
    let (first, shown) = match page {
        Page::Last => (newest, pages),
        Page::Nth(n) => (n.saturating_mul(per).min(newest), (n + 1).min(pages)),
    };

    fill_screen(
        &fb,
        match fill {
            Fill::Fatal => rgb(&fb, 0x60, 0x00, 0x00),
            Fill::Boot => 0,
        },
    );

    // The only array in this module and the one place the stack budget
    // stretches; `per <= MAX_ROWS` is what keeps the slice in bounds.
    let mut row_start = [Row { at: 0, line: 0 }; MAX_ROWS];
    let draw = per.min(total - first).min(MAX_ROWS);
    row_offsets(text, cols, first, &mut row_start[..draw]);

    let white = rgb(&fb, 0xFF, 0xFF, 0xFF);
    let alert = rgb(&fb, 0xFF, 0x50, 0x50);

    let mut inked = 0usize;
    let mut probes = 0usize;
    for (r, row) in row_start[..draw].iter().enumerate() {
        // **The colour comes from the record's `Level`**, so it holds for every
        // display row a wrapped line occupies rather than only the one the
        // marker happened to land on.
        let color = if view.is_alert(row.line as usize) { alert } else { white };
        let mut off = row.at as usize;
        let mut c = 0;
        while c < cols && off < len {
            let byte = text[off];
            if byte == b'\n' {
                break;
            }
            draw_glyph(&fb, c, r, byte, color);
            if watch == Watch::Yes {
                if let Some((bx, by)) = glyph_ink(byte) {
                    if inked.is_multiple_of(PROBE_STRIDE) && probes < PROBES - GRID_PROBES {
                        let (x, y) = (c * GLYPH_W + bx, r * GLYPH_H + by);
                        PROBE_AT[probes].store(((y as u32) << 16) | x as u32, Ordering::Relaxed);
                        probes += 1;
                    }
                    inked += 1;
                }
            }
            off += 1;
            c += 1;
        }
    }

    if pages > 1 {
        draw_footer(&fb, cols, grid_rows - 1, shown, pages, white);
    }

    flush_stores();
    if watch == Watch::Yes {
        sample_probes(&fb, probes);
    }
}

/// Read back what this paint left at each probe, after the grid has been added
/// to the ink the draw loop chose.
///
/// Read back rather than assumed from the colour asked for: a probe outside the
/// published byte count was never written, and one under the footer is whatever
/// the footer put there. What [`panel_carries_report`] compares against has to
/// be what is on the glass, or the first check would report an overwrite that
/// never happened.
fn sample_probes(fb: &Fb, ink: usize) {
    let mut n = ink.min(PROBES - GRID_PROBES);
    let w = (fb.width as usize).saturating_sub(1);
    let h = (fb.height as usize).saturating_sub(1);
    for i in 0..GRID_PROBES {
        // Corners included, which is where a taskbar and the strip below the
        // last cell row are, and where `Ppm::fill` reads.
        let (x, y) = (w * (i % GRID_COLS) / (GRID_COLS - 1), h * (i / GRID_COLS) / (GRID_ROWS - 1));
        PROBE_AT[n].store(((y as u32) << 16) | x as u32, Ordering::Relaxed);
        n += 1;
    }
    for i in 0..n {
        let at = PROBE_AT[i].load(Ordering::Relaxed);
        let px = get_pixel(fb, (at & 0xFFFF) as usize, (at >> 16) as usize);
        PROBE_PX[i].store(px, Ordering::Relaxed);
    }
    PROBE_N.store(n, Ordering::Relaxed);
}

/// Whether every probe still holds what the last paint left there.
///
/// No probes means nothing has been painted, and there is then nothing to put
/// back — which is why this answers yes rather than no.
fn panel_carries_report(fb: &Fb) -> bool {
    let n = PROBE_N.load(Ordering::Relaxed).min(PROBES);
    (0..n).all(|i| {
        let at = PROBE_AT[i].load(Ordering::Relaxed);
        get_pixel(fb, (at & 0xFFFF) as usize, (at >> 16) as usize)
            == PROBE_PX[i].load(Ordering::Relaxed)
    })
}

/// Put every store this module has made on the bus.
///
/// The scanout is write-combining, so a paint's last stores can sit in a
/// partly filled WC buffer with nothing to evict them. SFENCE is what drains
/// one (SDM Vol. 3A §11.3.1), and a fatal panic halts without ever giving the
/// buffer another reason to.
fn flush_stores() {
    // SAFETY: irreducible — `SFENCE` is the instruction, not a wrapper around
    // one, and `core::sync::atomic::fence` is a *compiler and CPU ordering*
    // barrier that emits no `SFENCE` on x86-64, so it would not drain a
    // write-combining buffer. Sound because the instruction touches no memory
    // and no register: it orders stores already issued. `nostack` because it
    // uses none, `preserves_flags` because `SFENCE` writes no flag.
    unsafe { core::arch::asm!("sfence", options(nostack, preserves_flags)) };
}

/// `[page 2/4]` on the bottom row, and the module's only formatting.
///
/// It is not decoration. The pager advances on a timer with no key to press,
/// so the artifact is a photograph of one page out of several: without this a
/// reader cannot tell which slice they caught, whether the head is above them,
/// or whether the screen is cycling at all rather than wedged.
fn draw_footer(fb: &Fb, cols: usize, row: usize, page: usize, pages: usize, color: u32) {
    let mut buf = [0u8; 24];
    let mut n = 0;
    for &b in b"[page " {
        buf[n] = b;
        n += 1;
    }
    n += write_num(&mut buf[n..], page);
    buf[n] = b'/';
    n += 1;
    n += write_num(&mut buf[n..], pages);
    buf[n] = b']';
    n += 1;
    for (c, &byte) in buf[..n.min(cols)].iter().enumerate() {
        draw_glyph(fb, c, row, byte, color);
    }
}

/// Decimal `v` into the front of `out`, returning the bytes written. `out` is
/// always the tail of a 24-byte buffer holding at most two numbers, and a page
/// count is bounded by `SNAPSHOT_CAP`, so ten digits of room is nine spare.
fn write_num(out: &mut [u8], v: usize) -> usize {
    let mut digits = [0u8; 20];
    let mut n = 0;
    let mut v = v;
    loop {
        digits[n] = b'0' + (v % 10) as u8;
        n += 1;
        v /= 10;
        if v == 0 || n == digits.len() {
            break;
        }
    }
    for i in 0..n.min(out.len()) {
        out[i] = digits[n - 1 - i];
    }
    n.min(out.len())
}

/// Whether the first and last framebuffer pages resolve in the *current* CR3.
///
/// Not `kernel_cr3()`: a panic in syscall context runs on a user address
/// space, which copies the kernel's top-half PML4 entries at creation. Shared
/// page directories propagate later mappings, but this proves it rather than
/// assuming it -- and it is what turns "the page tables are why we panicked"
/// into no console instead of a fault inside the panic handler.
fn mapped(fb: &Fb) -> bool {
    let base = fb.ptr as u64;
    let Some(last) = base.checked_add(fb.bytes.saturating_sub(1)) else {
        return false;
    };
    mm::paging::present_in_current_cr3(base) && mm::paging::present_in_current_cr3(last)
}

/// `pixel_format` is 0 for RGB and 1 for BGR (`bootloader/src/main.rs`). As a
/// little-endian u32 that is the byte order of the low three bytes.
fn rgb(fb: &Fb, r: u32, g: u32, b: u32) -> u32 {
    if fb.format == 0 {
        r | (g << 8) | (b << 16)
    } else {
        b | (g << 8) | (r << 16)
    }
}

/// What is on the glass at one pixel, or 0 where nothing may be read — the
/// same clamp [`put_pixel`] applies, so a position that could not be written
/// answers the same both ways and a probe on one is never a false alarm.
fn get_pixel(fb: &Fb, x: usize, y: usize) -> u32 {
    let Some(row) = (y as u64).checked_mul(fb.stride_px as u64) else { return 0 };
    let Some(idx) = row.checked_add(x as u64).and_then(|v| v.checked_mul(4)) else { return 0 };
    if idx.saturating_add(4) > fb.bytes {
        return 0;
    }
    // SAFETY: irreducible — a volatile read of the scanout has no safe
    // spelling, and the framebuffer is a `*mut u8` from the GOP descriptor
    // rather than anything `mm` allocated, so there is no bounds-carrying type
    // to route it through. Bounded by the three checked operations above:
    // `idx + 4 <= fb.bytes` was just established, and `validate` refused a
    // descriptor whose base is null or outside the direct map. Volatile because
    // the scanout is write-combining memory another agent scans out of.
    unsafe { core::ptr::read_volatile(fb.ptr.add(idx as usize) as *const u32) }
}

#[inline]
fn put_pixel(fb: &Fb, x: usize, y: usize, color: u32) {
    let Some(row) = (y as u64).checked_mul(fb.stride_px as u64) else { return };
    let Some(idx) = row.checked_add(x as u64).and_then(|v| v.checked_mul(4)) else { return };
    if idx.saturating_add(4) > fb.bytes {
        return;
    }
    // SAFETY: irreducible and bounded exactly as `get_pixel` is — the same
    // three checked operations, the same `validate`d descriptor, and the same
    // reason for volatile.
    unsafe { core::ptr::write_volatile(fb.ptr.add(idx as usize) as *mut u32, color) };
}

/// Base pointer for a row, given that `len` pixels will be written from it.
/// `None` means the row does not fit the published byte count, which for a
/// left-to-right top-to-bottom walk means neither does any later row.
fn row_base(fb: &Fb, y: usize, len: usize) -> Option<*mut u32> {
    let start = (y as u64).checked_mul(fb.stride_px as u64)?.checked_mul(4)?;
    let end = start.checked_add((len as u64).checked_mul(4)?)?;
    // SAFETY: irreducible — the whole point of this function is to hand
    // `fill_screen` a row pointer whose clamp has been proved once instead of
    // once per pixel, which the paragraph below argues is the difference
    // between a repaint nobody notices and one that doubles boot time. Bounded
    // by the `then`: `start` and `end` are checked products and `end <=
    // fb.bytes` gates the pointer's existence, so every one of the `len` `u32`s
    // written from it is inside the published byte count.
    (end <= fb.bytes).then(|| unsafe { fb.ptr.add(start as usize) as *mut u32 })
}

/// Paint the whole panel a colour no glyph contains, over whatever is there.
///
/// The actuator for "something drew on the glass behind the console's back".
/// Nothing else in reach can stage it: `DeviceType::Framebuffer` is claimed
/// exclusively so no second process can map the scanout, `boot_checkpoint`
/// returns the moment userland owns the screen, and the one painter that
/// ignores that claim — `render` — halts the machine on its way out, which
/// leaves nobody to type the command under test.
///
/// It covers the strip below the last glyph row too, which is the half of this
/// a console composing cell by cell can never reach on its own.
#[cfg(feature = "test-actuators")]
pub fn graffiti() {
    let Some(fb) = snapshot() else { return };
    if !mapped(&fb) {
        return;
    }
    log!("SYS_DEBUG: painting over the screen a userland process owns");
    fill_screen(&fb, rgb(&fb, 0x00, 0xC0, 0x00));
    flush_stores();
}

/// Erases whatever the compositor left behind, so nothing on screen is
/// ambiguous about which boot it came from.
///
/// Proves the clamp once per row rather than once per pixel: a boot checkpoint
/// repaints six times and a 2048x2048 panel is 4.2M pixels, so per-pixel
/// checked arithmetic here is the difference between a repaint nobody notices
/// and one that doubles boot time.
fn fill_screen(fb: &Fb, color: u32) {
    let width = fb.width as usize;
    for y in 0..fb.height as usize {
        let Some(row) = row_base(fb, y, width) else { return };
        for x in 0..width {
            // SAFETY: irreducible — `row_base` returns a pointer rather than a
            // slice precisely so this loop pays no per-pixel bound, and a
            // volatile store to the scanout has no safe spelling. Bounded by
            // `row_base`, which returned `Some` only after proving `width`
            // `u32`s from `row` are inside `fb.bytes`, and `x < width`.
            unsafe { core::ptr::write_volatile(row.add(x), color) };
        }
    }
}

/// The 16 rows the font draws a byte with. One mapping, because the probe
/// picker below has to name a pixel [`draw_glyph`] actually sets and a second
/// copy of this `match` would be free to disagree with it.
fn glyph(byte: u8) -> &'static [u8] {
    let ch = match byte {
        b'\t' => b' ',
        0x20..=0x7E => byte,
        _ => b'.',
    };
    let base = (ch - 0x20) as usize * GLYPH_H;
    &FONT[base..base + GLYPH_H]
}

/// A pixel of this byte's glyph, in its cell. `None` for a glyph with no ink,
/// which is the only kind a probe must refuse: on a blank cell the report and
/// whatever replaced it look identical.
fn glyph_ink(byte: u8) -> Option<(usize, usize)> {
    for (row, &bits) in glyph(byte).iter().enumerate() {
        for bit in 0..GLYPH_W {
            if bits & (0x80 >> bit) != 0 {
                return Some((bit, row));
            }
        }
    }
    None
}

fn draw_glyph(fb: &Fb, cell_x: usize, cell_y: usize, byte: u8, color: u32) {
    let ox = cell_x * GLYPH_W;
    let oy = cell_y * GLYPH_H;
    for (row, &bits) in glyph(byte).iter().enumerate() {
        if bits == 0 {
            continue;
        }
        for bit in 0..GLYPH_W {
            if bits & (0x80 >> bit) != 0 {
                put_pixel(fb, ox + bit, oy + row, color);
            }
        }
    }
}
